# Generated by LakehousePlumber
# Pipeline: dep_bindings
# FlowGroup: cdf_probe_flow

from pyspark.sql import DataFrame
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "dep_bindings"
FLOWGROUP_ID = "cdf_probe_flow"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_cdf_probe():
    """SQL source: load_cdf_probe"""
    df = spark.sql("""SELECT * FROM IDENTIFIER('acme_edw_dev.edw_bronze.helper_snapshot_dim')
WHERE id NOT IN (
  SELECT id
  FROM table_changes('acme_edw_dev.edw_bronze.helper_snapshot_dim', 0)
)
""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_silver.cdf_probe_out",
    comment="Materialized view: cdf_probe_out",
    table_properties={},
)
def cdf_probe_out():
    """Write to acme_edw_dev.edw_silver.cdf_probe_out from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_cdf_probe")

    return df
