#!/usr/bin/env node
/**
 * Regenerates `src/types/api.generated.ts` from the FastAPI backend's
 * OpenAPI schema, so Python↔TypeScript type drift surfaces as a tsc break
 * or a `git diff` on the committed generated file.
 *
 * Usage: `npm run gen:api` (from web_app/).
 *
 * Requires the repo's Python environment active (`pip install -e .` at the
 * repo root) so `python -c "from lhp.webapp.app import create_app"` works.
 * Override the interpreter with the PYTHON env var if needed.
 *
 * Steps:
 *   1. Dump the OpenAPI document — key-sorted for determinism — to
 *      `./openapi.json` (a gitignored, regenerable intermediate).
 *   2. Convert it to TypeScript via openapi-typescript.
 */
import { execFileSync } from 'node:child_process'
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import openapiTS, { astToString } from 'openapi-typescript'

const webAppDir = path.dirname(path.dirname(fileURLToPath(import.meta.url)))

const pythonCode = [
  'import json, os',
  // Any existing directory works: settings only need a readable root, and
  // .openapi() never runs the app lifespan.
  'os.environ.setdefault("LHP_WEBAPP_PROJECT_ROOT", ".")',
  'from lhp.webapp.app import create_app',
  'print(json.dumps(create_app().openapi(), sort_keys=True, indent=2))',
].join('\n')

const python = process.env.PYTHON ?? 'python'
let openapiJson
try {
  openapiJson = execFileSync(python, ['-c', pythonCode], {
    cwd: webAppDir,
    // stderr inherited: backend log lines stay visible but never pollute
    // the captured JSON on stdout.
    stdio: ['ignore', 'pipe', 'inherit'],
    encoding: 'utf8',
  })
} catch (err) {
  console.error(
    `gen-api: failed to dump the OpenAPI schema via "${python}". ` +
      'Is the repo Python env active (pip install -e . at the repo root)?',
  )
  throw err
}

const openapiPath = path.join(webAppDir, 'openapi.json')
writeFileSync(openapiPath, openapiJson)

const header = `/**
 * This file was auto-generated by openapi-typescript from the FastAPI
 * backend's OpenAPI schema (lhp.webapp). Do not edit by hand — regenerate
 * with \`npm run gen:api\` (requires the repo's Python env active).
 */
`

const ast = await openapiTS(JSON.parse(openapiJson))
const outPath = path.join(webAppDir, 'src', 'types', 'api.generated.ts')
writeFileSync(outPath, header + astToString(ast))

console.log(`gen-api: wrote ${path.relative(webAppDir, openapiPath)} and src/types/api.generated.ts`)
