# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: supplier_silver_dim

from functools import partial
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "supplier_silver_dim"


# ============================================================================
# TARGET TABLES
# ============================================================================

# Snapshot function embedded directly in generated code
from typing import Optional, Tuple
from pyspark.sql import DataFrame


def next_supplier_snapshot(
    latest_snapshot_version: Optional[int],
    *,
    catalog: str,
    schema: str,
    table: str,
) -> Optional[Tuple[DataFrame, int]]:

    if latest_snapshot_version is None:
        df = spark.sql(f"""
            SELECT * FROM acme_edw_dev.{schema}.{table}
            WHERE snapshot_id = (SELECT min(snapshot_id) FROM acme_edw_dev.{schema}.{table})
        """)

        min_snapshot_id = spark.sql(f"""
            SELECT min(snapshot_id) as min_id FROM acme_edw_dev.{schema}.{table}
        """).collect()[0].min_id

        return (df, min_snapshot_id)

    else:
        next_snapshot_result = spark.sql(f"""
            SELECT min(snapshot_id) as next_id
            FROM acme_edw_dev.{schema}.{table}
            WHERE snapshot_id > '{latest_snapshot_version}'
        """).collect()[0]

        if next_snapshot_result.next_id is None:
            return None

        next_snapshot_id = next_snapshot_result.next_id
        df = spark.sql(f"""
            SELECT * FROM acme_edw_dev.{schema}.{table}
            WHERE snapshot_id = '{next_snapshot_id}'
        """)

        return (df, next_snapshot_id)


# Create the streaming table for snapshot CDC
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.supplier_dim", comment="Streaming table: supplier_dim"
)

# Snapshot CDC mode using create_auto_cdc_from_snapshot_flow
dp.create_auto_cdc_from_snapshot_flow(
    target="acme_edw_dev.edw_silver.supplier_dim",
    source=partial(
        next_supplier_snapshot,
        catalog="acme_edw_dev",
        schema="edw_bronze",
        table="supplier",
    ),
    keys=["supplier_id"],
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_source_file_path",
        "_processing_timestamp",
        "snapshot_id",
        "last_modified_dt",
    ],
)
