# Generated by LakehousePlumber
# Pipeline: 17_delta_cdc
# FlowGroup: cdc_skip_change_commits

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "17_delta_cdc"
FLOWGROUP_ID = "cdc_skip_change_commits"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_inventory_latest():
    """Stream inventory latest state, skipping data-changing commits"""
    df = spark.readStream.option("skipChangeCommits", "true").table(
        "acme_edw_dev.edw_bronze.inventory"
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.inventory_latest",
    comment="Latest inventory state derived from skipChangeCommits stream",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.inventory_latest",
    name="f_inventory_latest",
    comment="Append flow to acme_edw_dev.edw_silver.inventory_latest",
)
def f_inventory_latest():
    """Append flow to acme_edw_dev.edw_silver.inventory_latest"""
    # Streaming flow
    df = spark.readStream.table("v_inventory_latest")

    return df
