# Generated by LakehousePlumber
# Pipeline: 17_delta_cdc
# FlowGroup: cdc_read_change_feed

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "17_delta_cdc"
FLOWGROUP_ID = "cdc_read_change_feed"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_orders_cdf():
    """Stream order changes via Delta Change Data Feed"""
    df = (
        spark.readStream.option("readChangeFeed", "true")
        .option("startingVersion", "0")
        .table("acme_edw_dev.edw_bronze.orders")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.orders_cdf",
    comment="CDF stream of orders into silver",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.orders_cdf",
    name="f_orders_cdf",
    comment="Append flow to acme_edw_dev.edw_silver.orders_cdf",
)
def f_orders_cdf():
    """Append flow to acme_edw_dev.edw_silver.orders_cdf"""
    # Streaming flow
    df = spark.readStream.table("v_orders_cdf")

    return df
