# Generated by LakehousePlumber
# Pipeline: 17_delta_cdc
# FlowGroup: cdc_starting_version

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "17_delta_cdc"
FLOWGROUP_ID = "cdc_starting_version"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_customers_cdf():
    """Stream customer changes from version 5, ignoring deletes"""
    df = (
        spark.readStream.option("readChangeFeed", "true")
        .option("startingVersion", "5")
        .option("ignoreDeletes", "true")
        .table("acme_edw_dev.edw_bronze.customers")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.customers_cdf",
    comment="CDF stream of customers (from v5, no deletes) into silver",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.customers_cdf",
    name="f_customers_cdf",
    comment="Append flow to acme_edw_dev.edw_silver.customers_cdf",
)
def f_customers_cdf():
    """Append flow to acme_edw_dev.edw_silver.customers_cdf"""
    # Streaming flow
    df = spark.readStream.table("v_customers_cdf")

    return df
