"""Compose ONE pipeline's gate-approved outputs into a deterministic wheel.

This is the keystone seam of wheel-mode packaging: it turns the in-memory
artifacts the commit path already holds (flowgroup ``formatted_code`` and
``custom_python_functions`` copy records) into a single content-addressed
``.whl`` plus its runner, reusing the pure ``identity`` math, the
``WheelBuilder`` archive assembler, and the ``runner`` renderer.

The load-bearing invariant is R4 (WHEEL_PACKAGING_SPEC §6.4): every ``.py``
packaged in the wheel is BYTE-IDENTICAL to what source mode writes to disk.
Source mode writes through :func:`lhp.utils.file_header.write_normalized`, so
every member here is normalized through the SAME ``normalize_content`` before
hashing/packing — the in-memory ``formatted_code`` / ``record.content`` are
PRE-normalization and must not be packed raw.

Hash scope (resolves §6.4 vs §6.5): the content hash covers every member EXCEPT
the synthesized flowgroup-package ``__init__.py`` (a packaging-only file, like
``.dist-info``); the wheel still INCLUDES that synth ``__init__``, and
``.dist-info`` is added by :class:`WheelBuilder`, not a member here.
"""

from __future__ import annotations

import logging
from collections.abc import Mapping
from dataclasses import dataclass
from pathlib import Path
from typing import Optional, Sequence

from ...models.processing import FlowgroupOutcome
from ...utils.file_header import normalize_content
from .identity import (
    content_hash,
    distribution_name,
    import_package_name,
    wheel_filename,
)
from .runner import build_runner_code
from .wheel_builder import WheelBuilder

logger = logging.getLogger(__name__)

# A single-comment synthesized ``__init__`` makes the flowgroup package a
# REGULAR package (not a namespace package), which the runner's
# ``pkgutil.iter_modules`` walk requires (WHEEL_PACKAGING_SPEC §6.4, §6.6).
_SYNTH_INIT_BODY = "# Generated by LakehousePlumber - flowgroup package\n"


@dataclass(frozen=True, slots=True)
class WheelPackageResult:
    """The complete in-memory result of packaging one pipeline as a wheel.

    INTERNAL transport (deliberately absent from ``lhp.api.__all__``; it IS
    part of ``lhp.core.packaging.__init__.__all__``). Carries everything the
    commit path (task C2) needs to write the runner under the source glob and
    the wheel under the ``_wheels/`` tree, plus the identity components C2
    threads into the generated bundle resource.

    ``frozen=True, slots=True`` for immutability and a small footprint.
    """

    wheel_bytes: bytes
    wheel_filename: str
    content_hash: str
    runner_code: str
    runner_filename: str
    import_package: str


class PipelinePackager:
    """Assemble a :class:`WheelPackageResult` from one pipeline's outcomes.

    Stateless: a single instance may package any number of pipelines. It owns
    only the member-mapping + assembly ORDER (WHEEL_PACKAGING_SPEC §6.4/§6.5);
    all identity math, archive bytes, and runner source come from the siblings.
    """

    def package(
        self,
        outcomes: Sequence[FlowgroupOutcome],
        *,
        output_dir: Path,
        pipeline: str,
        env: str,
        version: str,
        extra_package_modules: Optional[Mapping[str, str]] = None,
        extra_toplevel_files: Optional[Mapping[str, str]] = None,
    ) -> WheelPackageResult:
        """Package one pipeline's flowgroup outcomes into a wheel + runner.

        ``outcomes`` are the pipeline's per-flowgroup outcomes (the commit
        path's ``outcomes_in_order``); only successful ones contribute. Each
        contributes its ``formatted_code`` (the flowgroup module) and any
        ``custom_python_functions`` copy records. ``output_dir`` is the
        pipeline's source-mode output directory and is the ROOT every copy
        record's ``dest_path`` is made relative to.

        ``version`` is the LHP tool version (WHEEL_PACKAGING_SPEC §6.3); the
        CALLER passes ``get_version()`` — this method never calls it, keeping
        the seam pure and testable.

        ``extra_package_modules`` and ``extra_toplevel_files`` are two
        domain-agnostic ``relpath -> content`` buckets of extra generated
        members — packed under the flowgroup package and at the wheel top-level
        respectively (see :meth:`_build_members` for the exact arcnames). Both
        are normalized like every other member (R4) and BOTH are folded into the
        content hash, so changing either changes the wheel identity. Members
        dedupe by arcname.

        Returns a :class:`WheelPackageResult` with the wheel bytes, the wheel
        filename, the content hash, and the runner source/filename.
        """
        import_pkg = import_package_name(pipeline)

        members = self._build_members(
            outcomes,
            output_dir=output_dir,
            import_pkg=import_pkg,
            extra_package_modules=extra_package_modules,
            extra_toplevel_files=extra_toplevel_files,
        )

        # Hash covers every member EXCEPT the synth __init__ (§6.4/§6.5).
        synth_init_arc = f"{import_pkg}/__init__.py"
        chash = content_hash(
            {arc: data for arc, data in members.items() if arc != synth_init_arc}
        )
        dist = distribution_name(pipeline=pipeline, env=env, content_hash=chash)
        fname = wheel_filename(dist_name=dist, version=version)

        # The wheel INCLUDES the synth __init__; WheelBuilder adds .dist-info.
        wheel_bytes = WheelBuilder().build(members, dist_name=dist, version=version)

        runner_code = build_runner_code(import_package=import_pkg)
        runner_filename = f"{import_pkg}_runner.py"

        logger.debug(
            f"Packaged pipeline '{pipeline}' (env={env}): {len(members)} members, "
            f"content_hash={chash}, wheel={fname}"
        )

        return WheelPackageResult(
            wheel_bytes=wheel_bytes,
            wheel_filename=fname,
            content_hash=chash,
            runner_code=runner_code,
            runner_filename=runner_filename,
            import_package=import_pkg,
        )

    @staticmethod
    def _build_members(
        outcomes: Sequence[FlowgroupOutcome],
        *,
        output_dir: Path,
        import_pkg: str,
        extra_package_modules: Optional[Mapping[str, str]],
        extra_toplevel_files: Optional[Mapping[str, str]],
    ) -> dict[str, bytes]:
        """Build the ``arcname -> normalized bytes`` member map (R4).

        Mapping (WHEEL_PACKAGING_SPEC §6.4, R6):

          * flowgroup module ``formatted_code`` -> ``<import_pkg>/<name>.py``;
          * each copy record -> ``record.dest_path.relative_to(output_dir)`` as
            POSIX (``custom_python_functions`` ships TOP-LEVEL, incl. its own
            ``__init__.py``);
          * ``extra_package_modules`` -> ``<import_pkg>/<relpath>``,
            ``extra_toplevel_files`` -> ``<relpath>`` (top-level);
          * a synthesized ``<import_pkg>/__init__.py``.

        Every member's bytes = ``normalize_content(content).encode("utf-8")`` —
        byte-identical to source mode's on-disk ``write_normalized`` output.
        """
        members: dict[str, bytes] = {}

        for outcome in outcomes:
            if not outcome.success:
                continue

            code = outcome.formatted_code or ""
            if code.strip():
                arc = f"{import_pkg}/{outcome.flowgroup_name}.py"
                members[arc] = normalize_content(code).encode("utf-8")

            for record in outcome.copy_records:
                arc = record.dest_path.relative_to(output_dir).as_posix()
                members[arc] = normalize_content(record.content).encode("utf-8")

        for relpath, content in (extra_package_modules or {}).items():
            data = normalize_content(content).encode("utf-8")
            members[f"{import_pkg}/{relpath}"] = data
        for relpath, content in (extra_toplevel_files or {}).items():
            members[relpath] = normalize_content(content).encode("utf-8")

        members[f"{import_pkg}/__init__.py"] = normalize_content(
            _SYNTH_INIT_BODY
        ).encode("utf-8")

        return members
