# This pipeline creates a product performance materialized view
# Pipeline variable puts the generate files in the same folder for the pipeline to pick up
pipeline: acmi_edw_gold
# Flowgroup are conceptual artifacts and has no functional purpose
# there are used to group actions together in the generated files
flowgroup: product_performance_mv

actions:

  - name: product_performance_mv_sql
    type: load
    source:
      type: sql
      sql_path: "sql/gld/product_performance_mv.sql"        
    target: v_product_performance_mv_sql
    

  - name: write_product_performance_mv
    type: write
    source: v_product_performance_mv_sql
    write_target:
      type: materialized_view
      database: "{catalog}.{gold_schema}"
      table: "product_performance_mv" 