"""End-to-end integration tests for Bundle Manager business logic."""

import difflib
import hashlib
import os
import shutil
import time
from pathlib import Path

import pytest
from click.testing import CliRunner

from lhp.cli.main import cli


@pytest.mark.e2e
class TestBundleManagerE2E:
    @pytest.fixture(autouse=True)
    def setup_test_project(self, isolated_project):
        fixture_path = Path(__file__).parent / "fixtures" / "testing_project"
        self.project_root = isolated_project / "test_project"
        shutil.copytree(fixture_path, self.project_root)

        self.original_cwd = os.getcwd()
        os.chdir(self.project_root)

        self.generated_dir = self.project_root / "generated" / "dev"
        self.resources_dir = self.project_root / "resources" / "lhp"

        self._init_bundle_project()

        yield

        os.chdir(self.original_cwd)

    def _init_bundle_project(self):
        # Baselines are only used for comparison, never copied into working directories.
        if self.generated_dir.exists():
            shutil.rmtree(self.generated_dir)
        if self.resources_dir.exists():
            shutil.rmtree(self.resources_dir)

        self.generated_dir.mkdir(parents=True, exist_ok=True)
        self.resources_dir.mkdir(parents=True, exist_ok=True)

    def has_lhp_header(self, file_path: Path) -> bool:
        if not file_path.exists():
            return False
        content = file_path.read_text()
        return "Generated by LakehousePlumber" in content

    def run_bundle_sync(self) -> tuple:
        runner = CliRunner()
        pipeline_config = self.project_root / "config" / "pipeline_config.yaml"
        if pipeline_config.exists():
            result = runner.invoke(
                cli,
                [
                    "--verbose",
                    "generate",
                    "--env",
                    "dev",
                    "--pipeline-config",
                    "config/pipeline_config.yaml",
                ],
            )
        else:
            result = runner.invoke(cli, ["--verbose", "generate", "--env", "dev"])
        return result.exit_code, result.output

    def assert_log_contains(self, output: str, expected: str):
        assert expected.lower() in output.lower(), (
            f"Expected '{expected}' in output: {output}"
        )

    def test_pipeline_directory_resource_file_correspondence(self):
        """Test that directories under generated/{env}/ correspond to .pipeline.yml files."""
        # Run generation so the invariant is checked against real generated state.
        # The autouse _init_bundle_project wipes both generated/dev and resources/lhp,
        # so without this call both sets would be empty and the assertions vacuous.
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Generate should succeed: {output}"

        # Clean up baseline inconsistency - remove acmi_edw_tests.pipeline.yml
        # if it exists without a corresponding generated directory.
        orphaned_tests_file = self.resources_dir / "acmi_edw_tests.pipeline.yml"
        if orphaned_tests_file.exists():
            orphaned_tests_file.unlink()

        pipeline_dirs = set()
        if self.generated_dir.exists():
            pipeline_dirs = {d.name for d in self.generated_dir.iterdir() if d.is_dir()}

        resource_pipelines = set()
        if self.resources_dir.exists():
            for f in self.resources_dir.glob("*.pipeline.yml"):
                pipeline_name = f.name.replace(".pipeline.yml", "")
                resource_pipelines.add(pipeline_name)

        missing_dirs = resource_pipelines - pipeline_dirs
        extra_dirs = pipeline_dirs - resource_pipelines

        assert not missing_dirs, (
            f"Resource files exist but no directories: {missing_dirs}"
        )
        assert not extra_dirs, f"Directories exist but no resource files: {extra_dirs}"

    def test_BM1_1_regenerate_existing_lhp_managed_file(self):
        """BM-1_1: `lhp generate` wipes `resources/lhp/` and regenerates every `*.pipeline.yml` from current state."""
        pipeline_name = "acmi_edw_bronze"

        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generation should succeed: {output}"

        assert (self.generated_dir / pipeline_name).exists(), (
            "Pipeline directory should exist"
        )
        resource_file = self.resources_dir / f"{pipeline_name}.pipeline.yml"
        assert resource_file.exists(), "Resource file should exist"
        assert self.has_lhp_header(resource_file), (
            "Resource file should have LHP header"
        )

        original_mtime = resource_file.stat().st_mtime

        # Bump past filesystem mtime resolution (1s on common POSIX FSes).
        time.sleep(1.1)

        exit_code, output = self.run_bundle_sync()

        assert exit_code == 0, f"Second generate should succeed: {output}"
        new_mtime = resource_file.stat().st_mtime
        assert new_mtime > original_mtime, (
            "Resource file should be regenerated on every run (mtime should advance)"
        )

        baseline_resource = (
            self.project_root
            / "resources_baseline"
            / "lhp"
            / f"{pipeline_name}.pipeline.yml"
        )
        hash_result = self._compare_file_hashes(resource_file, baseline_resource)
        assert hash_result == "", f"Generated file should match baseline: {hash_result}"

    def test_BM3_create_new_resource_file_when_missing(self):
        """BM-3: Create new resource file when missing."""
        pipeline_name = "acmi_edw_bronze"

        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generation should succeed: {output}"

        assert (self.generated_dir / pipeline_name).exists(), (
            "Pipeline directory should exist"
        )
        resource_file = self.resources_dir / f"{pipeline_name}.pipeline.yml"
        if resource_file.exists():
            resource_file.unlink()
        assert not resource_file.exists(), "Resource file should not exist initially"

        exit_code, output = self.run_bundle_sync()

        assert exit_code == 0, f"Generate should succeed: {output}"
        assert resource_file.exists(), "Resource file should be created"
        assert self.has_lhp_header(resource_file), (
            "New resource file should have LHP header"
        )

        # Check rendered content (catalog/schema come from pipeline_config.yaml
        # project_defaults; the legacy ${var.default_pipeline_*} template
        # variables were removed in v0.8.7 — see docs/configure_catalog_schema.rst).
        content = resource_file.read_text()
        assert "catalog: acme_edw_dev" in content, (
            "Should have resolved catalog from pipeline_config.yaml project_defaults"
        )
        assert "schema: edw_bronze" in content, (
            "Should have resolved schema from per-pipeline entry in pipeline_config.yaml"
        )
        assert f"generated/${{bundle.target}}/{pipeline_name}" in content, (
            "Should have correct path"
        )

    def test_BM4_delete_orphaned_resource_file(self):
        """BM-4: Delete orphaned resource file."""
        # Use a resource file that won't be regenerated by lhp generate.
        pipeline_name = "fake_orphaned_pipeline"

        resource_file = self.resources_dir / f"{pipeline_name}.pipeline.yml"
        resource_file.write_text(
            "# Orphaned resource file\nresources:\n  pipelines: {}"
        )
        assert resource_file.exists(), "Orphaned resource file should exist initially"

        pipeline_dir = self.generated_dir / pipeline_name
        if pipeline_dir.exists():
            shutil.rmtree(pipeline_dir)
        assert not pipeline_dir.exists(), "Pipeline directory should not exist"

        exit_code, output = self.run_bundle_sync()

        assert exit_code == 0, f"Generate should succeed: {output}"
        assert not resource_file.exists(), (
            f"Orphaned resource file should be deleted: {resource_file}"
        )

    def test_BM7_output_directory_missing(self):
        """BM-7: Error when output directory missing."""
        if self.generated_dir.exists():
            shutil.rmtree(self.generated_dir)
        assert not self.generated_dir.exists(), "Generated directory should not exist"

        exit_code, output = self.run_bundle_sync()

        # Generate auto-creates missing directories; behavioral contract is exit_code == 0 plus resources/lhp existing.
        assert exit_code == 0, (
            f"Generate should auto-create missing directory: {output}"
        )
        assert self.generated_dir.exists(), (
            "Generated directory should be auto-created by `lhp generate`."
        )
        assert (self.project_root / "resources" / "lhp").exists(), (
            "Bundle sync must materialize resources/lhp directory."
        )

    def test_resources_lhp_wiped_on_every_run(self):
        """`resources/lhp/` is wiped on every generate; leftover files are removed."""
        # Pre-place a leftover user file directly inside `resources/lhp/`.
        # Under the new behavior, the entire `resources/lhp/` tree is wiped
        # before regeneration, so this file MUST disappear.
        self.resources_dir.mkdir(parents=True, exist_ok=True)
        leftover = self.resources_dir / "leftover_user_file.yml"
        leftover_content = (
            "# Leftover user-managed file inside resources/lhp/.\n"
            "# Wave-2 behavior: this file is wiped on every `lhp generate`.\n"
            "resources:\n"
            "  pipelines: {}\n"
        )
        leftover.write_text(leftover_content)
        assert leftover.exists(), "Precondition: leftover file should exist"

        exit_code, output = self.run_bundle_sync()

        assert exit_code == 0, f"Generate should succeed: {output}"
        assert not leftover.exists(), (
            "resources/lhp/leftover_user_file.yml should be wiped by generation"
        )

        # Bare `lhp generate` produces a non-trivial set of pipelines; we just verify the wipe didn't
        # prevent generation. Per-test baselines for tests that alter the fixture are out of scope here.
        generated_files = list(self.resources_dir.glob("*.pipeline.yml"))
        assert len(generated_files) >= 10, (
            f"Expected bare generate to produce >=10 pipeline YAMLs; "
            f"got {len(generated_files)}: {[f.name for f in generated_files]}"
        )

    def test_user_resources_outside_lhp_preserved(self):
        """User resource files outside `resources/lhp/` survive; files inside it are wiped."""
        resources_root = self.project_root / "resources"
        resources_root.mkdir(parents=True, exist_ok=True)

        # Pre-place two user-managed files OUTSIDE resources/lhp/.
        # These must survive `lhp generate` byte-for-byte.
        jobs_dir = resources_root / "jobs"
        jobs_dir.mkdir(parents=True, exist_ok=True)
        user_job_file = jobs_dir / "my_job.yml"
        user_job_content = (
            "# User-managed Databricks Asset Bundle job definition.\n"
            "# Wave-2 behavior: files outside resources/lhp/ are preserved as-is.\n"
            "resources:\n"
            "  jobs:\n"
            "    my_job:\n"
            "      name: my_job\n"
        )
        user_job_file.write_text(user_job_content)

        user_custom_file = resources_root / "custom_thing.yml"
        user_custom_content = (
            "# Arbitrary user-managed bundle resource (not a job, not a pipeline).\n"
            "# Wave-2 behavior: files outside resources/lhp/ are preserved as-is.\n"
            "resources:\n"
            "  experiments: {}\n"
        )
        user_custom_file.write_text(user_custom_content)

        # Pre-place a file INSIDE resources/lhp/ to verify nested dirs are wiped too.
        self.resources_dir.mkdir(parents=True, exist_ok=True)
        lhp_jobs_subdir = self.resources_dir / "jobs"
        lhp_jobs_subdir.mkdir(parents=True, exist_ok=True)
        nested_note = lhp_jobs_subdir / "note.txt"
        nested_note.write_text("user note placed inside resources/lhp/jobs/\n")

        user_job_hash_before = hashlib.sha256(user_job_file.read_bytes()).hexdigest()
        user_custom_hash_before = hashlib.sha256(
            user_custom_file.read_bytes()
        ).hexdigest()

        exit_code, output = self.run_bundle_sync()

        assert exit_code == 0, f"Generate should succeed: {output}"

        assert user_job_file.exists(), (
            "resources/jobs/my_job.yml must survive the generate run"
        )
        assert user_custom_file.exists(), (
            "resources/custom_thing.yml must survive the generate run"
        )

        user_job_hash_after = hashlib.sha256(user_job_file.read_bytes()).hexdigest()
        user_custom_hash_after = hashlib.sha256(
            user_custom_file.read_bytes()
        ).hexdigest()
        assert user_job_hash_before == user_job_hash_after, (
            "resources/jobs/my_job.yml content must be unchanged"
        )
        assert user_custom_hash_before == user_custom_hash_after, (
            "resources/custom_thing.yml content must be unchanged"
        )

        # Casualty: anything inside resources/lhp/, including subdirs, is gone.
        assert not nested_note.exists(), (
            "resources/lhp/jobs/note.txt must be wiped by the generate run"
        )

    def test_databricks_yml_not_mutated(self):
        """`databricks.yml` is byte-identical before and after `lhp generate`."""
        databricks_yml = self.project_root / "databricks.yml"
        assert databricks_yml.exists(), (
            f"Precondition: databricks.yml must exist in fixture: {databricks_yml}"
        )

        hash_before = hashlib.sha256(databricks_yml.read_bytes()).hexdigest()

        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Generate should succeed: {output}"

        hash_after = hashlib.sha256(databricks_yml.read_bytes()).hexdigest()
        assert hash_before == hash_after, (
            "databricks.yml must not be mutated by `lhp generate`.\n"
            f"  pre-run sha256:  {hash_before}\n"
            f"  post-run sha256: {hash_after}"
        )

    def test_missing_catalog_schema_fails_fast(self):
        """Missing catalog/schema in pipeline_config.yaml fails fast with doc reference.

        Uses the dedicated `testing_project_no_catalog_schema` fixture variant.
        """
        # Replace autouse-copied fixture with the variant that has pipeline_config.yaml
        # WITHOUT catalog/schema (neither per-pipeline nor `project_defaults`).
        variant_fixture = (
            Path(__file__).parent / "fixtures" / "testing_project_no_catalog_schema"
        )
        assert variant_fixture.exists(), (
            f"Fixture variant must exist: {variant_fixture}"
        )

        os.chdir(self.original_cwd)
        shutil.rmtree(self.project_root)
        shutil.copytree(variant_fixture, self.project_root)
        os.chdir(self.project_root)

        self.generated_dir = self.project_root / "generated" / "dev"
        self.resources_dir = self.project_root / "resources" / "lhp"
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        self.resources_dir.mkdir(parents=True, exist_ok=True)

        # Try to separate stderr from stdout when supported by the installed
        # Click version; older versions only support `mix_stderr=False` while
        # newer ones combine streams unless an alternate API is used.
        try:
            runner = CliRunner(mix_stderr=False)
            separate_streams = True
        except TypeError:
            runner = CliRunner()
            separate_streams = False

        result = runner.invoke(
            cli,
            [
                "--verbose",
                "generate",
                "--env",
                "dev",
                "--pipeline-config",
                "config/pipeline_config.yaml",
            ],
        )

        stderr_text = (getattr(result, "stderr", "") if separate_streams else "") or ""
        stdout_text = result.output or ""
        assert result.exit_code != 0, (
            "Generate must fail fast when catalog/schema are missing from "
            f"pipeline_config.yaml. Got exit_code={result.exit_code}, "
            f"stdout={stdout_text!r}, stderr={stderr_text!r}"
        )

        # Expected: error output references the configure_catalog_schema doc
        # via the LHPError-formatted "More info" link. The structured signal
        # `configure_catalog_schema` (page slug) must appear and the error
        # code `LHP-CFG-026` must be present; full wording is not asserted to
        # keep the test resilient to copy edits. When stderr cannot be
        # separated from stdout on the installed Click, accept the union.
        combined = stderr_text + stdout_text
        assert "configure_catalog_schema" in combined, (
            "Error output must reference the configure_catalog_schema doc page.\n"
            f"  stderr: {stderr_text!r}\n"
            f"  stdout: {stdout_text!r}"
        )
        assert "LHP-CFG-026" in combined, (
            "Error output must include the structured code LHP-CFG-026.\n"
            f"  stderr: {stderr_text!r}\n"
            f"  stdout: {stdout_text!r}"
        )

    def test_validate_fails_on_missing_catalog_schema(self) -> None:
        """Validate fails fast (LHP-CFG-026) when catalog/schema are missing.

        Validate-side mirror of `test_missing_catalog_schema_fails_fast`
        (constitution §9.24): generate and validate now share one preflight
        (`_run_project_preflight`), so `lhp validate` runs the bundle
        catalog/schema preflight and surfaces LHP-CFG-026 with the same
        `configure_catalog_schema` doc-link that generate emits.

        Uses the dedicated `testing_project_no_catalog_schema` fixture variant
        (pipeline_config.yaml with no catalog/schema, neither per-pipeline nor
        `project_defaults`). The fixture ships a `databricks.yml`, so validate
        REQUIRES `-pc` on it -- hence we invoke `lhp validate` WITH
        `--pipeline-config`.

        Surfacing asymmetry (asserted deliberately, not an oversight): the
        bundle catalog/schema preflight emits a PROJECT-level issue. Generate
        raises it as a full LHPError, so its rendering includes the
        `configure_catalog_schema` "More info" doc-link
        (`test_missing_catalog_schema_fails_fast` asserts that). Validate folds
        project-level preflight issues into the batch `error_message` (a short
        `Error [LHP-CFG-026]: ...` title); `render_error_panel`, which is what
        prints doc-links, runs only for PER-PIPELINE issues, so the doc-link
        does NOT appear in validate's output. This test therefore asserts the
        contract validate actually guarantees -- non-zero exit + LHP-CFG-026 --
        and intentionally does NOT assert the doc-link string. The error code
        (the structured, machine-readable signal §9.24 cares about) is
        symmetric across both paths; the cosmetic doc-link rendering is not.
        """
        variant_fixture = (
            Path(__file__).parent / "fixtures" / "testing_project_no_catalog_schema"
        )
        assert variant_fixture.exists(), (
            f"Fixture variant must exist: {variant_fixture}"
        )

        os.chdir(self.original_cwd)
        shutil.rmtree(self.project_root)
        shutil.copytree(variant_fixture, self.project_root)
        os.chdir(self.project_root)

        self.generated_dir = self.project_root / "generated" / "dev"
        self.resources_dir = self.project_root / "resources" / "lhp"
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        self.resources_dir.mkdir(parents=True, exist_ok=True)

        # Separate stderr from stdout when the installed Click supports it
        # (mirror test_missing_catalog_schema_fails_fast).
        try:
            runner = CliRunner(mix_stderr=False)
            separate_streams = True
        except TypeError:
            runner = CliRunner()
            separate_streams = False

        # `lhp validate` requires -pc on bundle projects; the variant ships a databricks.yml.
        result = runner.invoke(
            cli,
            [
                "--verbose",
                "validate",
                "--env",
                "dev",
                "--pipeline-config",
                "config/pipeline_config.yaml",
            ],
        )

        stderr_text = (getattr(result, "stderr", "") if separate_streams else "") or ""
        stdout_text = result.output or ""
        assert result.exit_code != 0, (
            "Validate must fail when catalog/schema are missing from "
            f"pipeline_config.yaml. Got exit_code={result.exit_code}, "
            f"stdout={stdout_text!r}, stderr={stderr_text!r}"
        )

        combined = stderr_text + stdout_text
        assert "LHP-CFG-026" in combined, (
            "Validate's bundle preflight must surface LHP-CFG-026.\n"
            f"  stderr: {stderr_text!r}\n"
            f"  stdout: {stdout_text!r}"
        )
        # NB: the `configure_catalog_schema` doc-link is intentionally NOT
        # asserted here -- see the docstring's "Surfacing asymmetry" note.
        # Validate folds the project-level bundle issue into the short batch
        # error message, which carries the code but not the doc-link.

    def _snapshot_tree(self, *roots: Path) -> dict:
        """SHA-256 every file under the given roots; map relative path to hex.

        Used to prove preflight runs BEFORE any side effects: the generated
        and resources trees must be byte-identical before and after a failed
        invocation. Same idiom as ``test_databricks_yml_not_mutated`` above.
        """
        snapshot = {}
        for root in roots:
            if not root.exists():
                continue
            for file_path in root.rglob("*"):
                if file_path.is_file():
                    rel = str(file_path.relative_to(self.project_root))
                    snapshot[rel] = hashlib.sha256(file_path.read_bytes()).hexdigest()
        return snapshot

    def test_preflight_blocks_when_pc_missing_and_bundle_enabled(self):
        """B-gate: bundle enabled + no -pc -> LHP-CFG-023 with zero side effects.

        Seed both ``resources/lhp/`` and ``generated/dev/`` with sentinel files
        before invocation and verify their SHA-256 is unchanged afterwards.
        Proves the wipe in ``generate_command.py`` is reached only AFTER
        ``require_pipeline_config_flag`` succeeds.
        """
        sentinel_resources = self.resources_dir / "sentinel.yml"
        sentinel_generated = self.generated_dir / "sentinel.txt"
        sentinel_resources.write_text("# sentinel -- must survive preflight failure\n")
        sentinel_generated.write_text("sentinel\n")

        before = self._snapshot_tree(self.resources_dir, self.generated_dir)

        # Invoke WITHOUT --pipeline-config to trigger B-gate.
        runner = CliRunner()
        result = runner.invoke(cli, ["generate", "--env", "dev"])

        assert result.exit_code != 0, (
            f"Generate must fail when bundle is enabled and -pc is omitted. "
            f"exit_code={result.exit_code}, output={result.output!r}"
        )
        assert "LHP-CFG-023" in result.output, (
            f"Expected LHP-CFG-023 in CLI output; got:\n{result.output}"
        )

        after = self._snapshot_tree(self.resources_dir, self.generated_dir)
        assert before == after, (
            "Preflight failure must not touch resources/lhp/ or generated/<env>/.\n"
            f"  before: {before}\n"
            f"  after:  {after}"
        )
        assert sentinel_resources.exists(), "Sentinel under resources/ was wiped"
        assert sentinel_generated.exists(), "Sentinel under generated/ was wiped"

    def test_preflight_blocks_when_catalog_missing_in_pc(self):
        """A+: catalog/schema missing -> LHP-CFG-026 aggregated; zero side effects.

        Uses the dedicated ``testing_project_no_catalog_schema`` fixture variant
        (which already ships a pipeline_config.yaml with no catalog/schema).
        """
        variant_fixture = (
            Path(__file__).parent / "fixtures" / "testing_project_no_catalog_schema"
        )
        os.chdir(self.original_cwd)
        shutil.rmtree(self.project_root)
        shutil.copytree(variant_fixture, self.project_root)
        os.chdir(self.project_root)
        self.generated_dir = self.project_root / "generated" / "dev"
        self.resources_dir = self.project_root / "resources" / "lhp"
        self.generated_dir.mkdir(parents=True, exist_ok=True)
        self.resources_dir.mkdir(parents=True, exist_ok=True)

        sentinel_resources = self.resources_dir / "sentinel.yml"
        sentinel_generated = self.generated_dir / "sentinel.txt"
        sentinel_resources.write_text("# sentinel\n")
        sentinel_generated.write_text("sentinel\n")

        before = self._snapshot_tree(self.resources_dir, self.generated_dir)

        runner = CliRunner()
        result = runner.invoke(
            cli,
            [
                "generate",
                "--env",
                "dev",
                "--pipeline-config",
                "config/pipeline_config.yaml",
            ],
        )

        assert result.exit_code != 0, (
            f"Generate must fail when catalog/schema are missing. "
            f"exit_code={result.exit_code}, output={result.output!r}"
        )
        assert "LHP-CFG-026" in result.output, (
            f"Expected LHP-CFG-026 in CLI output; got:\n{result.output}"
        )
        assert "simple_pipeline" in result.output, (
            f"Aggregated error must name the failing pipeline; got:\n{result.output}"
        )

        after = self._snapshot_tree(self.resources_dir, self.generated_dir)
        assert before == after, (
            "Preflight failure must not touch resources/lhp/ or generated/<env>/."
        )

    def test_preflight_passes_with_project_defaults_only(self):
        """Happy path: project_defaults sets catalog/schema -> exit 0.

        Uses the standard testing_project fixture (which has project_defaults
        with catalog/schema set). Verifies generation completes and resource
        files are produced under ``resources/lhp/``.
        """
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, (
            f"Generate should succeed with valid project_defaults; output:\n{output}"
        )
        pipeline_files = list(self.resources_dir.glob("*.pipeline.yml"))
        assert pipeline_files, (
            f"Expected *.pipeline.yml files under {self.resources_dir}; "
            f"found: {list(self.resources_dir.iterdir())}"
        )

    def test_preflight_runs_in_dry_run(self):
        """Preflight executes under ``--dry-run`` -- proves it is not gated by side effects.

        Invokes with ``--dry-run`` AND without ``-pc``; expects ``LHP-CFG-023``
        specifically (B-gate raised before any work). This is the inverse
        guarantee of ``check_substitution_file``: dry-run does NOT skip
        preflight.
        """
        runner = CliRunner()
        result = runner.invoke(cli, ["generate", "--env", "dev", "--dry-run"])

        assert result.exit_code != 0, (
            f"Dry-run must still fail B-gate. "
            f"exit_code={result.exit_code}, output={result.output!r}"
        )
        assert "LHP-CFG-023" in result.output, (
            f"Expected LHP-CFG-023 specifically (not a generic error); "
            f"got:\n{result.output}"
        )

    def test_bundle_yaml_regenerated_every_run(self):
        """Every `*.pipeline.yml` in `resources/lhp/` is regenerated on every run."""
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generate should succeed: {output}"

        pipeline_files = sorted(self.resources_dir.glob("*.pipeline.yml"))
        assert pipeline_files, (
            f"At least one *.pipeline.yml must exist after run 1 in {self.resources_dir}"
        )

        mtimes_run1 = {f.name: f.stat().st_mtime for f in pipeline_files}

        # Bump past filesystem mtime resolution (1s on common POSIX FSes).
        time.sleep(1.1)

        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Second generate should succeed: {output}"

        pipeline_files_after = sorted(self.resources_dir.glob("*.pipeline.yml"))
        names_after = {f.name for f in pipeline_files_after}
        names_before = set(mtimes_run1.keys())
        assert names_after == names_before, (
            "Set of *.pipeline.yml files should be identical across runs.\n"
            f"  before: {sorted(names_before)}\n"
            f"  after:  {sorted(names_after)}"
        )

        not_regenerated = []
        for f in pipeline_files_after:
            new_mtime = f.stat().st_mtime
            old_mtime = mtimes_run1[f.name]
            if new_mtime <= old_mtime:
                not_regenerated.append(
                    f"{f.name}: run1_mtime={old_mtime}, run2_mtime={new_mtime}"
                )

        assert not not_regenerated, (
            "Every *.pipeline.yml must be regenerated (strictly newer mtime) on "
            "each run. Files that were not regenerated:\n  "
            + "\n  ".join(not_regenerated)
        )

    def test_baseline_hash_comparison_dev_environment(self):
        """Test that generate -e dev produces identical files to baseline using hashes."""
        baseline_dir = self.project_root / "generated_baseline" / "dev"
        assert baseline_dir.exists(), "Baseline directory should exist for comparison"

        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Generate should succeed: {output}"

        dev_generated_dir = self.project_root / "generated" / "dev"

        hash_differences = self._compare_directory_hashes(
            dev_generated_dir, baseline_dir
        )

        if hash_differences:
            details = "\n".join(
                f"  {i}. {diff}" for i, diff in enumerate(hash_differences, 1)
            )
            raise AssertionError(
                f"Generated files differ from baseline: "
                f"{len(hash_differences)} differences found\n{details}"
            )

    def test_include_directive_filtering(self):
        """Test that include directive filters pipelines correctly and matches baseline."""
        lhp_config_file = self.project_root / "lhp.yaml"
        original_content = self._enable_include_filtering(lhp_config_file)

        original_cwd = os.getcwd()

        try:
            os.chdir(self.project_root)

            runner = CliRunner()
            # Use pipeline config if it exists (same logic as run_bundle_sync)
            pipeline_config = self.project_root / "config" / "pipeline_config.yaml"
            if pipeline_config.exists():
                result = runner.invoke(
                    cli,
                    [
                        "--verbose",
                        "generate",
                        "--env",
                        "dev",
                        "--pipeline-config",
                        "config/pipeline_config.yaml",
                    ],
                    catch_exceptions=False,
                )
            else:
                result = runner.invoke(
                    cli,
                    ["--verbose", "generate", "--env", "dev"],
                    catch_exceptions=False,
                )
            exit_code, output = result.exit_code, result.output

            assert exit_code == 0, (
                f"Generate with include filtering should succeed: {output}"
            )

            dev_generated_dir = self.project_root / "generated" / "dev"

            self._verify_selective_generation(dev_generated_dir)

            generated_raw_dir = dev_generated_dir / "acmi_edw_raw"
            baseline_raw_dir = (
                self.project_root / "generated_baseline" / "dev" / "acmi_edw_raw"
            )

            assert generated_raw_dir.exists(), (
                f"acmi_edw_raw directory should be generated: {generated_raw_dir}"
            )
            assert baseline_raw_dir.exists(), (
                f"acmi_edw_raw baseline should exist: {baseline_raw_dir}"
            )

            hash_differences = self._compare_directory_hashes(
                generated_raw_dir, baseline_raw_dir
            )
            if hash_differences:
                details = "\n".join(
                    f"  {i}. {diff}" for i, diff in enumerate(hash_differences, 1)
                )
                raise AssertionError(
                    f"Generated acmi_edw_raw files differ from baseline: "
                    f"{len(hash_differences)} differences\n{details}"
                )

            generated_resource_file = self.resources_dir / "acmi_edw_raw.pipeline.yml"
            baseline_resource_file = (
                self.project_root
                / "resources_baseline"
                / "lhp"
                / "acmi_edw_raw.pipeline.yml"
            )

            assert generated_resource_file.exists(), (
                f"acmi_edw_raw resource file should be generated: {generated_resource_file}"
            )
            assert baseline_resource_file.exists(), (
                f"acmi_edw_raw resource baseline should exist: {baseline_resource_file}"
            )

            resource_hash_diff = self._compare_file_hashes(
                generated_resource_file, baseline_resource_file
            )
            if resource_hash_diff:
                raise AssertionError(
                    f"Generated acmi_edw_raw resource file differs from baseline: "
                    f"{resource_hash_diff}"
                )

        finally:
            os.chdir(original_cwd)
            self._restore_lhp_config(lhp_config_file, original_content)

    def test_multi_environment_consistency(self):
        """Test same files exist across environments with non-empty content."""
        environments = ["dev", "tst", "prod"]
        file_structures = {}

        for env in environments:
            env_generated_dir = self._clean_and_generate(env)
            file_structures[env] = self._get_file_structure_with_sizes(
                env_generated_dir
            )

        dev_files = set(file_structures["dev"].keys())
        for env in ["tst", "prod"]:
            env_files = set(file_structures[env].keys())
            missing_files = dev_files - env_files
            extra_files = env_files - dev_files

            assert not missing_files, f"Files missing in {env}: {missing_files}"
            assert not extra_files, f"Extra files in {env}: {extra_files}"

        empty_files = {}
        for env in environments:
            empty_files[env] = [
                file_path
                for file_path, size in file_structures[env].items()
                if size == 0
            ]

        for env in environments:
            if empty_files[env]:
                raise AssertionError(f"Empty files found in {env}: {empty_files[env]}")

    def test_flowgroup_deletion_triggers_cleanup(self):
        """Test that deleting flowgroup YAML cleans up generated files."""
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generation should succeed: {output}"

        dev_generated_dir = self.project_root / "generated" / "dev"

        generated_files_before = list(dev_generated_dir.rglob("*.py"))
        assert len(generated_files_before) > 0, "Should have generated files initially"

        flowgroup_file = (
            self.project_root / "pipelines" / "02_bronze" / "customer_bronze.yaml"
        )
        assert flowgroup_file.exists(), f"Flowgroup file should exist: {flowgroup_file}"

        original_content = flowgroup_file.read_text()
        flowgroup_file.unlink()

        try:
            exit_code, output = self.run_bundle_sync()
            assert exit_code == 0, (
                f"Generation after flowgroup deletion should succeed: {output}"
            )

            # Verify corresponding generated files are cleaned up.
            # Scope the search to acmi_edw_bronze; a global rglob picks up
            # unrelated pipelines that legitimately reference "customer_bronze"
            # in their own filenames (e.g. blueprint-derived flowgroups under
            # acme_edw_bp_bronze).
            bronze_dir = dev_generated_dir / "acmi_edw_bronze"
            remaining_customer_bronze_files = (
                list(bronze_dir.rglob("*customer_bronze*"))
                if bronze_dir.exists()
                else []
            )

            assert len(remaining_customer_bronze_files) == 0, (
                f"Customer bronze generated files not cleaned up: {remaining_customer_bronze_files}"
            )

        finally:
            # Restore the deleted file for other tests
            flowgroup_file.write_text(original_content)

    def test_pipeline_directory_deletion_cleanup(self):
        """Test deleting pipeline directory cleans up entire generated pipeline."""
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generation should succeed: {output}"

        dev_generated_dir = self.project_root / "generated" / "dev"

        bronze_generated_dir = dev_generated_dir / "acmi_edw_bronze"
        assert bronze_generated_dir.exists(), (
            f"Bronze generated directory should exist: {bronze_generated_dir}"
        )
        bronze_files_before = list(bronze_generated_dir.rglob("*"))
        assert len(bronze_files_before) > 0, (
            "Should have bronze generated files initially"
        )

        bronze_pipeline_dir = self.project_root / "pipelines" / "02_bronze"
        assert bronze_pipeline_dir.exists(), (
            f"Bronze pipeline directory should exist: {bronze_pipeline_dir}"
        )

        try:
            shutil.rmtree(bronze_pipeline_dir)

            exit_code, output = self.run_bundle_sync()
            assert exit_code == 0, (
                f"Generation after pipeline directory deletion should succeed: {output}"
            )

            assert not bronze_generated_dir.exists(), (
                f"Generated pipeline directory should be deleted: {bronze_generated_dir}"
            )

        finally:
            pass

    def _compare_directory_hashes(
        self, generated_dir: Path, baseline_dir: Path
    ) -> list:
        def get_file_hash(file_path: Path) -> str:
            with open(file_path, "rb") as f:
                return hashlib.sha256(f.read()).hexdigest()

        differences = []

        # Exclude __pycache__ from both sides.
        generated_files = {
            f.relative_to(generated_dir): f
            for f in generated_dir.rglob("*")
            if f.is_file() and "__pycache__" not in f.parts
        }
        baseline_files = {
            f.relative_to(baseline_dir): f
            for f in baseline_dir.rglob("*")
            if f.is_file() and "__pycache__" not in f.parts
        }

        only_in_generated = set(generated_files.keys()) - set(baseline_files.keys())
        for file_path in only_in_generated:
            differences.append(f"Extra file in generated: {file_path}")

        only_in_baseline = set(baseline_files.keys()) - set(generated_files.keys())
        for file_path in only_in_baseline:
            differences.append(f"Missing file from generated: {file_path}")

        common_files = set(generated_files.keys()) & set(baseline_files.keys())
        for file_path in common_files:
            try:
                generated_hash = get_file_hash(generated_files[file_path])
                baseline_hash = get_file_hash(baseline_files[file_path])

                if generated_hash != baseline_hash:
                    try:
                        with open(generated_files[file_path], "r") as f:
                            generated_lines = f.readlines()
                        with open(baseline_files[file_path], "r") as f:
                            baseline_lines = f.readlines()

                        diff = list(
                            difflib.unified_diff(
                                baseline_lines,
                                generated_lines,
                                fromfile=f"baseline/{file_path}",
                                tofile=f"generated/{file_path}",
                                lineterm="",
                                n=3,
                            )
                        )

                        # Limit diff output to first 50 lines for readability
                        diff_output = "\n".join(diff[:50])
                        if len(diff) > 50:
                            diff_output += (
                                f"\n... ({len(diff) - 50} more lines omitted)"
                            )

                        differences.append(
                            f"Content differs (hash mismatch): {file_path}\n"
                            f"    Generated: {generated_hash}\n"
                            f"    Baseline:  {baseline_hash}\n"
                            f"    Diff:\n{diff_output}"
                        )
                    except Exception as e:
                        differences.append(
                            f"Content differs (hash mismatch): {file_path}\n"
                            f"    Generated: {generated_hash}\n"
                            f"    Baseline:  {baseline_hash}\n"
                            f"    (Could not compute diff: {e})"
                        )
            except (OSError, IOError, UnicodeDecodeError) as e:
                differences.append(f"Error comparing {file_path}: {e}")

        return differences

    def _clean_and_generate(self, env: str):
        env_generated_dir = self.project_root / "generated" / env

        if env_generated_dir.exists():
            shutil.rmtree(env_generated_dir)

        runner = CliRunner()
        pipeline_config = self.project_root / "config" / "pipeline_config.yaml"
        if pipeline_config.exists():
            result = runner.invoke(
                cli,
                [
                    "--verbose",
                    "generate",
                    "--env",
                    env,
                    "--pipeline-config",
                    "config/pipeline_config.yaml",
                ],
            )
        else:
            result = runner.invoke(cli, ["--verbose", "generate", "--env", env])
        assert result.exit_code == 0, f"Generation failed for {env}: {result.output}"

        return env_generated_dir

    def _get_file_structure_with_sizes(self, directory: Path) -> dict:
        file_sizes = {}
        if not directory.exists():
            return file_sizes

        for file_path in directory.rglob("*"):
            if file_path.is_file():
                try:
                    rel_path = file_path.relative_to(directory)
                    file_sizes[rel_path] = file_path.stat().st_size
                except (OSError, IOError):
                    pass

        return file_sizes

    def _enable_include_filtering(self, lhp_config_file: Path) -> str:
        """The `include:` directive only filters hand-written flowgroups; without a parallel
        `instance_include:` blueprint instances would still be discovered from the default glob."""
        original_content = lhp_config_file.read_text()

        lines = original_content.split("\n")
        modified_lines = []

        for i, line in enumerate(lines):
            # Lines are 0-indexed, so line 9 is index 8, line 10 is index 9
            if i == 8 and line.strip().startswith("# include:"):
                modified_lines.append("include:")
            elif i == 9 and line.strip().startswith('#   - "01_raw_ingestion/**"'):
                modified_lines.append('  - "01_raw_ingestion/**"')
            else:
                modified_lines.append(line)

        # Append a matching instance_include so blueprints are filtered too.
        modified_lines.append("instance_include:")
        modified_lines.append('  - "01_raw_ingestion/**"')

        modified_content = "\n".join(modified_lines)
        lhp_config_file.write_text(modified_content)

        return original_content

    def _restore_lhp_config(self, lhp_config_file: Path, original_content: str):
        lhp_config_file.write_text(original_content)

    def _verify_selective_generation(self, dev_generated_dir: Path):
        if not dev_generated_dir.exists():
            raise AssertionError(
                f"Generated directory should exist: {dev_generated_dir}"
            )

        generated_dirs = {d.name for d in dev_generated_dir.iterdir() if d.is_dir()}

        expected_dirs = {"acmi_edw_raw"}
        unexpected_dirs = generated_dirs - expected_dirs
        missing_dirs = expected_dirs - generated_dirs

        if unexpected_dirs:
            raise AssertionError(
                f"Unexpected pipeline directories generated (include filtering failed): {unexpected_dirs}"
            )

        if missing_dirs:
            raise AssertionError(
                f"Expected pipeline directories missing: {missing_dirs}"
            )

    def _compare_file_hashes(self, file1: Path, file2: Path) -> str:
        def get_file_hash(file_path: Path) -> str:
            with open(file_path, "rb") as f:
                return hashlib.sha256(f.read()).hexdigest()

        try:
            hash1 = get_file_hash(file1)
            hash2 = get_file_hash(file2)

            if hash1 != hash2:
                return f"Hash mismatch: {file1.name} (generated) vs {file2.name} (baseline)"

            return ""

        except (OSError, IOError, UnicodeDecodeError) as e:
            return f"Error comparing files: {e}"

    def test_BM14_python_function_overwrite_behavior(self):
        """BM-14: Test that same source file changes overwrite existing copied file correctly."""
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generation should succeed: {output}"

        copied_file = (
            self.generated_dir
            / "sample_python_func_pipeline"
            / "custom_python_functions"
            / "sample_func.py"
        )
        assert copied_file.exists(), f"Copied file should exist: {copied_file}"

        content = copied_file.read_text()
        assert content.startswith("# LHP-SOURCE: py_functions/sample_func.py"), (
            "Should have simple LHP-SOURCE header"
        )

        original_source = self.project_root / "py_functions" / "sample_func.py"
        original_content = original_source.read_text()
        modified_content = original_content.replace(
            "df_input: DataFrame", "df_input_MODIFIED: DataFrame"
        )
        original_source.write_text(modified_content)

        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Regeneration should succeed: {output}"

        custom_functions_dir = (
            self.generated_dir
            / "sample_python_func_pipeline"
            / "custom_python_functions"
        )
        python_files = list(custom_functions_dir.glob("*.py"))
        python_file_names = [f.name for f in python_files if f.name != "__init__.py"]

        assert len(python_file_names) == 1, (
            f"Expected exactly 1 Python file, got {len(python_file_names)}: {python_file_names}"
        )
        assert "sample_func.py" in python_file_names, "Should have sample_func.py"

        updated_content = copied_file.read_text()
        assert "df_input_MODIFIED: DataFrame" in updated_content, (
            "Copied file should contain source modifications"
        )
        assert updated_content.startswith(
            "# LHP-SOURCE: py_functions/sample_func.py"
        ), "Should maintain simple header"

        print("✅ Phase 3: File correctly overwritten with new content")
        print("✅ BM-14: Python function overwrite behavior working correctly")

    def test_BM15_python_function_conflict_failure(self):
        """BM-15: Test that different source files with same name trigger clear failure."""
        exit_code, output = self.run_bundle_sync()
        assert exit_code == 0, f"Initial generation should succeed: {output}"

        print("✅ Phase 1: Initial generation completed")

        first_source = self.project_root / "py_functions" / "first_source.py"
        first_content = '''def transform_data(df):
    """First version of the function."""
    return df.withColumn("source", lit("FIRST"))
'''
        first_source.write_text(first_content)

        conflict_source = self.project_root / "py_functions" / "conflict_source.py"
        conflict_content = '''def transform_data(df):
    """Conflicting version with same destination name."""
    return df.withColumn("source", lit("CONFLICT"))
'''
        conflict_source.write_text(conflict_content)

        print("✅ Phase 2: Created source files for conflict scenario")

        from lhp.core.codegen import PythonFileCopier
        from lhp.errors import PythonFunctionConflictError

        copier = PythonFileCopier()
        custom_functions_dir = (
            self.generated_dir
            / "sample_python_func_pipeline"
            / "custom_python_functions"
        )
        dest_file = custom_functions_dir / "transformer.py"

        first_header = "# LHP-SOURCE: py_functions/first_source.py\n# Generated by LakehousePlumber\n\n"
        copier.copy_python_file(
            "py_functions/first_source.py", dest_file, first_header + first_content
        )

        print("✅ Phase 3: First file copied successfully")

        try:
            conflict_header = "# LHP-SOURCE: py_functions/conflict_source.py\n# Generated by LakehousePlumber\n\n"
            copier.copy_python_file(
                "py_functions/conflict_source.py",  # Different source!
                dest_file,  # Same destination!
                conflict_header + conflict_content,
            )
            raise AssertionError("Expected PythonFunctionConflictError to be raised")
        except PythonFunctionConflictError as e:
            print("✅ Conflict correctly detected and failed with error:")
            print(f"   {e!s}")

            assert "py_functions/first_source.py" in str(e), (
                "Should mention existing source"
            )
            assert "py_functions/conflict_source.py" in str(e), (
                "Should mention new source"
            )
            assert "transformer.py" in str(e), "Should mention destination file"

            assert e.existing_source == "py_functions/first_source.py"
            assert e.new_source == "py_functions/conflict_source.py"
            assert "transformer.py" in e.destination

        print("✅ Phase 4: Conflict detection working correctly")

        result = copier.copy_python_file(
            "py_functions/first_source.py",  # Same source as before
            dest_file,
            first_header + first_content,
        )
        assert result is False, (
            "Second copy of same source should be skipped (deduplicated)"
        )

        print("✅ Phase 5: Deduplication working correctly")
        print("✅ BM-15: Python function conflict failure working correctly")
