"""Tests for bundle resource YAML Jinja2 template functionality."""

import shutil
import tempfile
from pathlib import Path
from unittest.mock import Mock, patch

import pytest
import yaml

from lhp.bundle.exceptions import BundleResourceError
from lhp.bundle.manager import BundleManager


class TestBundleJinja2Templates:
    def setup_method(self):
        self.temp_dir = Path(tempfile.mkdtemp())
        self.project_root = self.temp_dir / "project"
        self.project_root.mkdir()
        self.generated_dir = self.project_root / "generated"
        self.generated_dir.mkdir()
        self.resources_dir = self.project_root / "resources" / "lhp"

        config_file = self.project_root / "pipeline_config.yaml"
        config_file.write_text(
            "project_defaults:\n"
            "  catalog: test_catalog\n"
            "  schema: test_schema\n"
            "  serverless: true\n"
        )

        self.manager = BundleManager(
            self.project_root, pipeline_config_path=str(config_file)
        )

    def teardown_method(self):
        shutil.rmtree(self.temp_dir)

    def test_basic_jinja2_template_rendering(self):
        """Should render basic template with standard pipeline name."""
        pipeline_name = "raw_ingestion"

        content = self.manager.generate_resource_file_content(
            pipeline_name, self.generated_dir, "dev"
        )

        assert content is not None
        assert isinstance(content, str)
        assert len(content) > 0
        assert "Generated by LakehousePlumber" in content
        assert f"Bundle Resource for {pipeline_name}" in content
        assert "resources:" in content
        assert "pipelines:" in content
        assert f"{pipeline_name}_pipeline:" in content

    def test_template_variable_substitution(self):
        """Should properly substitute {{ pipeline_name }} variable."""
        pipeline_names = ["bronze_load", "silver_transformations", "gold_aggregations"]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )

            assert f"Bundle Resource for {pipeline_name}" in content
            assert f"{pipeline_name}_pipeline:" in content
            assert f"name: {pipeline_name}_pipeline" in content
            assert (
                f"include: ${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}/**"
                in content
            )
            assert (
                f"${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}"
                in content
            )
            assert "{{ pipeline_name }}" not in content
            assert "{{pipeline_name}}" not in content

    def test_empty_pipeline_directory_template(self):
        """Should render template even with no Python files."""
        pipeline_name = "data_quality_checks"

        content = self.manager.generate_resource_file_content(
            pipeline_name, self.generated_dir, "dev"
        )

        assert content is not None
        assert isinstance(content, str)
        assert len(content) > 0
        assert (
            f"include: ${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}/**"
            in content
        )
        assert (
            f"root_path: ${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}"
            in content
        )
        assert f"{pipeline_name}_pipeline:" in content
        assert "- glob:" in content

    def test_very_long_pipeline_names(self):
        """Should handle very long pipeline names without truncation."""
        long_pipeline_name = "bronze_raw_data_ingestion_from_external_systems_including_legacy_databases_and_api_endpoints_with_comprehensive_data_validation_and_quality_checks_for_enterprise_data_warehouse_bronze_layer_processing"

        assert len(long_pipeline_name) >= 190
        assert len(long_pipeline_name) <= 200

        content = self.manager.generate_resource_file_content(
            long_pipeline_name, self.generated_dir, "dev"
        )

        assert f"Bundle Resource for {long_pipeline_name}" in content
        assert f"{long_pipeline_name}_pipeline:" in content
        assert f"name: {long_pipeline_name}_pipeline" in content
        assert (
            f"include: ${{workspace.file_path}}/generated/${{bundle.target}}/{long_pipeline_name}/**"
            in content
        )
        assert (
            f"${{workspace.file_path}}/generated/${{bundle.target}}/{long_pipeline_name}"
            in content
        )
        assert "resources:" in content
        assert "- glob:" in content

    def test_invalid_pipeline_names_error_handling(self):
        """Should handle null/empty pipeline names gracefully."""
        invalid_names = ["", "   ", None]

        for invalid_name in invalid_names:
            try:
                content = self.manager.generate_resource_file_content(
                    invalid_name, self.generated_dir, "dev"
                )

                if content:
                    assert isinstance(content, str)
                    assert "resources:" in content

            except (TypeError, ValueError, AttributeError) as e:
                assert invalid_name in [None, "", "   "]
                assert len(str(e)) > 0

        special_chars_name = "test@#$%^&*()"
        content = self.manager.generate_resource_file_content(
            special_chars_name, self.generated_dir, "dev"
        )

        assert content is not None
        assert special_chars_name in content

    def test_generated_yaml_syntax_validation(self):
        """Should generate syntactically valid YAML output."""
        import yaml

        pipeline_names = [
            "raw_ingestion",
            "bronze_load",
            "silver_transforms",
            "gold_aggregations",
        ]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )

            try:
                parsed_yaml = yaml.safe_load(content)

                assert parsed_yaml is not None
                assert isinstance(parsed_yaml, dict)
                assert "resources" in parsed_yaml
                assert "pipelines" in parsed_yaml["resources"]

                pipeline_key = f"{pipeline_name}_pipeline"
                assert pipeline_key in parsed_yaml["resources"]["pipelines"]

                pipeline_config = parsed_yaml["resources"]["pipelines"][pipeline_key]
                assert "name" in pipeline_config
                assert "libraries" in pipeline_config
                assert "root_path" in pipeline_config

            except yaml.YAMLError as e:
                pytest.fail(
                    f"Generated YAML is invalid for pipeline '{pipeline_name}': {e}"
                )

    def test_glob_pattern_format_correctness(self):
        """Should generate correct glob pattern: ../../generated/{{ pipeline_name }}/**"""
        import yaml

        pipeline_names = ["raw_ingestion", "bronze_processing", "silver_analytics"]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )
            parsed_yaml = yaml.safe_load(content)

            pipeline_key = f"{pipeline_name}_pipeline"
            libraries = parsed_yaml["resources"]["pipelines"][pipeline_key]["libraries"]

            assert len(libraries) == 1
            assert "glob" in libraries[0]

            glob_config = libraries[0]["glob"]
            assert "include" in glob_config

            expected_pattern = f"${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}/**"
            actual_pattern = glob_config["include"]

            assert actual_pattern == expected_pattern, (
                f"Expected '{expected_pattern}', got '{actual_pattern}'"
            )

            for library in libraries:
                assert "notebook" not in library, (
                    "Should not contain individual notebook entries"
                )

    def test_root_path_format_correctness(self):
        """Should generate correct root_path: ${workspace.file_path}/generated/{{ pipeline_name }}"""
        import yaml

        pipeline_names = ["bronze_load", "silver_transforms", "gold_metrics"]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )
            parsed_yaml = yaml.safe_load(content)

            pipeline_key = f"{pipeline_name}_pipeline"
            pipeline_config = parsed_yaml["resources"]["pipelines"][pipeline_key]

            assert "root_path" in pipeline_config

            expected_root_path = (
                f"${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}"
            )
            actual_root_path = pipeline_config["root_path"]

            assert actual_root_path == expected_root_path, (
                f"Expected '{expected_root_path}', got '{actual_root_path}'"
            )
            assert "${workspace.file_path}" in actual_root_path
            assert f"/generated/${{bundle.target}}/{pipeline_name}" in actual_root_path

    def test_yaml_structure_completeness(self):
        """Should include all required YAML fields (libraries, root_path, etc.)"""
        import yaml

        pipeline_name = "bronze_data_processing"
        content = self.manager.generate_resource_file_content(
            pipeline_name, self.generated_dir, "dev"
        )
        parsed_yaml = yaml.safe_load(content)

        assert "resources" in parsed_yaml
        assert "pipelines" in parsed_yaml["resources"]

        pipeline_key = f"{pipeline_name}_pipeline"
        assert pipeline_key in parsed_yaml["resources"]["pipelines"]

        pipeline_config = parsed_yaml["resources"]["pipelines"][pipeline_key]

        required_fields = [
            "name",
            "catalog",
            "schema",
            "libraries",
            "root_path",
            "configuration",
        ]
        for field in required_fields:
            assert field in pipeline_config, f"Missing required field: {field}"

        assert pipeline_config["name"] == f"{pipeline_name}_pipeline"
        assert pipeline_config["catalog"] == "test_catalog"
        assert pipeline_config["schema"] == "test_schema"

        libraries = pipeline_config["libraries"]
        assert isinstance(libraries, list)
        assert len(libraries) == 1
        assert "glob" in libraries[0]

        configuration = pipeline_config["configuration"]
        assert isinstance(configuration, dict)
        assert "bundle.sourcePath" in configuration

    def test_template_engine_integration(self):
        """Should integrate properly with bundle manager's Jinja2 environment via composition."""
        from lhp.core.codegen.template_renderer import TemplateRenderer

        assert hasattr(self.manager, "template_renderer")
        assert isinstance(self.manager.template_renderer, TemplateRenderer)
        assert hasattr(self.manager.template_renderer, "env")
        assert self.manager.template_renderer.env is not None
        assert hasattr(self.manager.template_renderer, "render_template")
        assert callable(self.manager.template_renderer.render_template)

        context = {
            "pipeline_name": "integration_test",
            "pipeline_config": {
                "serverless": True,
                "edition": "ADVANCED",
                "channel": "CURRENT",
                "continuous": False,
            },
        }
        content = self.manager.template_renderer.render_template(
            "bundle/pipeline_resource.yml.j2", context
        )

        assert content is not None
        assert isinstance(content, str)
        assert "integration_test" in content
        assert "integration_test_pipeline:" in content
        assert "tojson" in self.manager.template_renderer.env.filters
        assert "toyaml" in self.manager.template_renderer.env.filters

        # Verify the loader is wired to the lhp package templates.
        from jinja2 import PackageLoader

        loader = self.manager.template_renderer.env.loader
        assert isinstance(loader, PackageLoader)
        assert loader.package_name == "lhp"
        assert loader.package_path == "templates"

    def test_template_loading_from_package(self):
        """Should load .j2 template file from package resources."""
        template_name = "bundle/pipeline_resource.yml.j2"

        try:
            template = self.manager.template_renderer.env.get_template(template_name)
            assert template is not None
            assert template.name == template_name

            context = {
                "pipeline_name": "package_test",
                "pipeline_config": {
                    "serverless": True,
                    "edition": "ADVANCED",
                    "channel": "CURRENT",
                    "continuous": False,
                },
            }
            rendered = template.render(**context)

            assert rendered is not None
            assert isinstance(rendered, str)
            assert "package_test" in rendered

        except Exception as e:
            pytest.fail(f"Failed to load template '{template_name}': {e}")

        from pathlib import Path

        import lhp

        lhp_path = Path(lhp.__file__).parent
        template_path = lhp_path / "templates" / "bundle" / "pipeline_resource.yml.j2"

        assert template_path.exists(), f"Template file not found at {template_path}"
        assert template_path.is_file(), f"Template path is not a file: {template_path}"

    def test_template_context_building(self):
        """Should build proper context with required variables."""
        from unittest.mock import Mock

        original_render = self.manager.template_renderer.render_template

        captured_contexts = []

        def mock_render(template_name, context):
            captured_contexts.append((template_name, context))
            return original_render(template_name, context)

        self.manager.template_renderer.render_template = mock_render

        try:
            pipeline_names = ["context_test", "bronze_processing", "silver_analytics"]

            for pipeline_name in pipeline_names:
                self.manager.generate_resource_file_content(
                    pipeline_name, self.generated_dir, "dev"
                )

            assert len(captured_contexts) == len(pipeline_names)

            for i, (template_name, context) in enumerate(captured_contexts):
                assert template_name == "bundle/pipeline_resource.yml.j2"

                assert isinstance(context, dict)
                assert "pipeline_name" in context
                assert "pipeline_config" in context
                assert "catalog" in context  # may be None
                assert "schema" in context  # may be None
                # Drives the pass-through loop in pipeline_resource.yml.j2
                assert "explicitly_rendered_keys" in context

                expected_name = pipeline_names[i]
                assert context["pipeline_name"] == expected_name

                assert len(context) == 5, (
                    f"Context should contain 5 keys, got: {context.keys()}"
                )

        finally:
            self.manager.template_renderer.render_template = original_render

    def test_template_context_has_resolved_values(self):
        """Should pass resolved (substituted) config values to template."""
        config_file = self.project_root / "config" / "pipeline_config.yaml"
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text("""
---
pipeline: token_test
catalog: "${catalog}"
schema: "${bronze_schema}"
serverless: false
clusters:
  - label: default
    node_type_id: "${node_type}"
    policy_id: "${policy_id}"
""")

        sub_file = self.project_root / "substitutions" / "dev.yaml"
        sub_file.parent.mkdir(parents=True, exist_ok=True)
        sub_file.write_text("""
dev:
  catalog: resolved_catalog
  bronze_schema: resolved_schema
  node_type: Standard_D8ds_v5
  policy_id: resolved-policy-123
""")

        manager_with_config = BundleManager(self.project_root, str(config_file))

        captured_context = None
        original_render = manager_with_config.template_renderer.render_template

        def mock_render(template_name, context):
            nonlocal captured_context
            captured_context = context
            return original_render(template_name, context)

        manager_with_config.template_renderer.render_template = mock_render

        try:
            manager_with_config.generate_resource_file_content(
                "token_test", self.generated_dir, "dev"
            )

            assert captured_context is not None
            assert captured_context["catalog"] == "resolved_catalog"
            assert captured_context["schema"] == "resolved_schema"

            config = captured_context["pipeline_config"]
            assert config["catalog"] == "resolved_catalog"
            assert config["schema"] == "resolved_schema"
            assert config["clusters"][0]["node_type_id"] == "Standard_D8ds_v5"
            assert config["clusters"][0]["policy_id"] == "resolved-policy-123"

        finally:
            manager_with_config.template_renderer.render_template = original_render

    def test_template_rendering_error_handling(self):
        """Should handle Jinja2 errors gracefully (missing variables, etc.)"""
        from unittest.mock import patch

        from jinja2 import TemplateNotFound, UndefinedError

        from lhp.errors import LHPConfigError

        with patch.object(
            self.manager.template_renderer.env, "get_template"
        ) as mock_get_template:
            mock_get_template.side_effect = TemplateNotFound(
                "bundle/missing_template.yml.j2"
            )

            with pytest.raises(LHPConfigError, match=r"Template .* not found"):
                self.manager.template_renderer.render_template(
                    "bundle/missing_template.yml.j2", {"pipeline_name": "test"}
                )

        with patch.object(
            self.manager.template_renderer.env, "get_template"
        ) as mock_get_template:
            mock_template = mock_get_template.return_value
            mock_template.render.side_effect = UndefinedError(
                "'missing_var' is undefined"
            )

            with pytest.raises(LHPConfigError, match="undefined variable"):
                self.manager.template_renderer.render_template(
                    "bundle/pipeline_resource.yml.j2", {}
                )

        pipeline_name = "error_handling_test"
        content = self.manager.generate_resource_file_content(
            pipeline_name, self.generated_dir, "dev"
        )

        assert content is not None
        assert pipeline_name in content
        assert "resources:" in content

    def test_no_template_syntax_in_output(self):
        """Should ensure all {{ }} template syntax is resolved in final output."""
        # Test with various pipeline names to ensure comprehensive coverage
        pipeline_names = [
            "simple_test",
            "complex_pipeline_with_long_name",
            "test-with-dashes",
            "test_with_underscores",
            "123numeric_start",
        ]

        jinja2_patterns = [
            "{{",
            "}}",
            "{%",
            "%}",
            "{#",
            "#}",
            "{% for",
            "{% if",
            "{% set",
            "{{ pipeline_name }}",
        ]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )

            for pattern in jinja2_patterns:
                assert pattern not in content, (
                    f"Found Jinja2 syntax '{pattern}' in output for pipeline '{pipeline_name}'"
                )

            assert pipeline_name in content, (
                f"Pipeline name '{pipeline_name}' not found in output - template may not have rendered properly"
            )
            assert "resources:" in content
            assert "pipelines:" in content

    def test_lhp_header_preservation(self):
        """Should preserve correct LHP generated header comment."""
        pipeline_names = [
            "header_test",
            "bronze_processing",
            "complex_data_transformation",
        ]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )

            lines = content.split("\n")

            assert len(lines) > 0, "Generated content should not be empty"
            first_line = lines[0].strip()

            expected_header = (
                f"# Generated by LakehousePlumber - Bundle Resource for {pipeline_name}"
            )
            assert first_line == expected_header, (
                f"Expected header '{expected_header}', got '{first_line}'"
            )
            assert "Generated by LakehousePlumber" in first_line
            assert "Bundle Resource for" in first_line
            assert pipeline_name in first_line
            assert first_line.startswith("#"), "Header should be a YAML comment"

            yaml_lines = [
                line
                for line in lines[1:]
                if line.strip() and not line.strip().startswith("#")
            ]
            assert len(yaml_lines) > 0, "Should have YAML content after header"
            assert yaml_lines[0].startswith("resources:"), (
                "First YAML line should be 'resources:'"
            )

    def test_replace_individual_notebooks_with_glob(self):
        """Should replace individual notebook format with glob pattern."""
        import yaml

        pipeline_names = ["glob_test", "bronze_ingestion", "silver_transformation"]

        for pipeline_name in pipeline_names:
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )
            parsed_yaml = yaml.safe_load(content)

            pipeline_key = f"{pipeline_name}_pipeline"
            libraries = parsed_yaml["resources"]["pipelines"][pipeline_key]["libraries"]

            assert len(libraries) == 1, "Should have exactly one library entry"
            library_entry = libraries[0]

            assert "glob" in library_entry, "Library entry should use 'glob' key"
            assert "notebook" not in library_entry, (
                "Should not have individual 'notebook' entries"
            )
            assert "file" not in library_entry, (
                "Should not have individual 'file' entries"
            )
            assert "jar" not in library_entry, (
                "Should not have individual 'jar' entries"
            )

            glob_config = library_entry["glob"]
            assert "include" in glob_config, "Glob should have 'include' pattern"

            expected_pattern = f"${{workspace.file_path}}/generated/${{bundle.target}}/{pipeline_name}/**"
            actual_pattern = glob_config["include"]
            assert actual_pattern == expected_pattern, (
                f"Expected pattern '{expected_pattern}', got '{actual_pattern}'"
            )

            # root_path legitimately contains the path — check only specific library patterns
            legacy_library_patterns = [
                f"notebook: ../../generated/dev/{pipeline_name}/",
                f"path: ../../generated/dev/{pipeline_name}/",
                "- notebook:",
                "- file:",
                "- jar:",
            ]

            for pattern in legacy_library_patterns:
                assert pattern not in content, (
                    f"Found legacy library pattern '{pattern}' in output"
                )

            expected_contexts = [
                f"root_path: ${{workspace.file_path}}/generated/dev/{pipeline_name}",
                f"include: ../../generated/dev/{pipeline_name}/**",
            ]

            path_pattern = f"generated/dev/{pipeline_name}"
            total_occurrences = content.count(path_pattern)
            expected_occurrences = sum(
                1 for context in expected_contexts if context in content
            )

            assert total_occurrences == expected_occurrences, (
                f"Path pattern appears {total_occurrences} times but only {expected_occurrences} are in expected contexts"
            )

    def test_no_notebook_path_iteration(self):
        """Should not require iteration through individual notebook paths."""
        import os
        from unittest.mock import MagicMock, patch

        with (
            patch("os.listdir") as mock_listdir,
            patch("os.path.exists") as mock_exists,
            patch("pathlib.Path.glob") as mock_glob,
        ):
            mock_listdir.return_value = []
            mock_exists.return_value = True
            mock_glob.return_value = []

            pipeline_name = "no_iteration_test"
            content = self.manager.generate_resource_file_content(
                pipeline_name, self.generated_dir, "dev"
            )

            assert content is not None
            assert isinstance(content, str)
            assert pipeline_name in content
            assert "resources:" in content

            mock_listdir.assert_not_called()
            mock_glob.assert_not_called()

        import inspect

        method_sig = inspect.signature(self.manager.generate_resource_file_content)
        param_names = list(method_sig.parameters.keys())

        assert param_names == [
            "pipeline_name",
            "output_dir",
            "env",
        ], (
            f"Expected 'pipeline_name', 'output_dir', and 'env' parameters, got {param_names}"
        )

        removed_methods = [
            "_get_notebook_paths_for_pipeline",
            "_scan_pipeline_directory",
            "_list_notebook_files",
        ]

        for method_name in removed_methods:
            assert not hasattr(self.manager, method_name), (
                f"Method '{method_name}' should have been removed during migration"
            )

    def test_corrupted_resource_file_handling(self):
        """Should handle corrupted existing resource files gracefully."""
        from unittest.mock import patch

        pipeline_name = "corruption_test"
        content = self.manager.generate_resource_file_content(
            pipeline_name, self.generated_dir, "dev"
        )

        assert content is not None
        assert isinstance(content, str)
        assert pipeline_name in content

        # TemplateNotFound is wrapped in LHPConfigError by the template renderer
        from lhp.errors import LHPConfigError

        with patch.object(
            self.manager.template_renderer.env, "get_template"
        ) as mock_get_template:
            from jinja2 import TemplateNotFound

            mock_get_template.side_effect = TemplateNotFound(
                "bundle/pipeline_resource.yml.j2"
            )

            with pytest.raises(LHPConfigError, match="not found"):
                self.manager.generate_resource_file_content(
                    "test_pipeline", self.generated_dir, "dev"
                )

        with patch.object(
            self.manager.template_renderer, "render_template"
        ) as mock_render:
            mock_render.side_effect = Exception("Template rendering failed")

            try:
                self.manager.generate_resource_file_content(
                    "test_pipeline", self.generated_dir, "dev"
                )
                pytest.fail("Expected template rendering error to be raised")
            except Exception as e:
                assert "Template rendering failed" in str(e)

        recovery_content = self.manager.generate_resource_file_content(
            "recovery_test", self.generated_dir, "dev"
        )
        assert recovery_content is not None
        assert "recovery_test" in recovery_content

    def test_invalid_template_output_detection(self):
        """Should detect when template produces invalid YAML."""
        from unittest.mock import patch

        import yaml

        pipeline_name = "validation_test"
        content = self.manager.generate_resource_file_content(
            pipeline_name, self.generated_dir, "dev"
        )

        try:
            parsed = yaml.safe_load(content)
            assert parsed is not None
            assert isinstance(parsed, dict)
        except yaml.YAMLError:
            pytest.fail("Normal template output should produce valid YAML")

        with patch.object(
            self.manager.template_renderer, "render_template"
        ) as mock_render:
            invalid_yaml_outputs = [
                "resources:\n  pipelines:\n    - invalid: [unclosed",
                "resources: {\n  pipelines: {\n    test:",
                "resources:\n  pipelines:\n    @invalid_key: value",
                "{{unclosed_template",
            ]

            for invalid_output in invalid_yaml_outputs:
                mock_render.return_value = invalid_output

                result = self.manager.generate_resource_file_content(
                    "test", self.generated_dir, "dev"
                )

                assert result == invalid_output

                try:
                    yaml.safe_load(result)
                    pytest.fail(
                        f"Invalid YAML should have failed parsing: {invalid_output[:50]}..."
                    )
                except yaml.YAMLError:
                    pass

        recovery_content = self.manager.generate_resource_file_content(
            "recovery_test", self.generated_dir, "dev"
        )
        assert recovery_content is not None

        try:
            yaml.safe_load(recovery_content)
        except yaml.YAMLError:
            pytest.fail("Recovery content should produce valid YAML")

    def test_template_renders_instance_pool_id(self):
        """Should render instance_pool_id and omit node_type_id when not present."""
        config_file = self.project_root / "config" / "pipeline_config.yaml"
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text("""
project_defaults:
  catalog: test_catalog
  schema: test_schema
  serverless: false
  edition: ADVANCED

---
pipeline: pool_pipeline
clusters:
  - label: default
    instance_pool_id: 1010-095823-mud11-pool-i204xeov
    autoscale:
      min_workers: 1
      max_workers: 5
      mode: ENHANCED
""")
        manager = BundleManager(self.project_root, str(config_file))
        content = manager.generate_resource_file_content(
            "pool_pipeline", self.generated_dir, "dev"
        )

        parsed = yaml.safe_load(content)
        assert parsed is not None

        pipeline = parsed["resources"]["pipelines"]["pool_pipeline_pipeline"]

        cluster = pipeline["clusters"][0]
        assert cluster["instance_pool_id"] == "1010-095823-mud11-pool-i204xeov"
        assert "node_type_id" not in cluster

    def test_template_renders_both_node_type_and_pool(self):
        """Should render both node_type_id and instance_pool_id when both present."""
        config_file = self.project_root / "config" / "pipeline_config.yaml"
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text("""
project_defaults:
  catalog: test_catalog
  schema: test_schema
  serverless: false
  edition: ADVANCED

---
pipeline: mixed_pipeline
clusters:
  - label: default
    node_type_id: Standard_D16ds_v5
    instance_pool_id: 1010-095823-mud11-pool-i204xeov
    autoscale:
      min_workers: 1
      max_workers: 5
""")
        manager = BundleManager(self.project_root, str(config_file))
        content = manager.generate_resource_file_content(
            "mixed_pipeline", self.generated_dir, "dev"
        )

        parsed = yaml.safe_load(content)
        cluster = parsed["resources"]["pipelines"]["mixed_pipeline_pipeline"][
            "clusters"
        ][0]

        assert cluster["node_type_id"] == "Standard_D16ds_v5"
        assert cluster["instance_pool_id"] == "1010-095823-mud11-pool-i204xeov"

    def test_template_renders_driver_instance_pool_id(self):
        """Should render driver_instance_pool_id when present."""
        config_file = self.project_root / "config" / "pipeline_config.yaml"
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text("""
project_defaults:
  catalog: test_catalog
  schema: test_schema
  serverless: false
  edition: ADVANCED

---
pipeline: driver_pool_pipeline
clusters:
  - label: default
    instance_pool_id: worker-pool-123
    driver_instance_pool_id: driver-pool-456
    autoscale:
      min_workers: 1
      max_workers: 3
""")
        manager = BundleManager(self.project_root, str(config_file))
        content = manager.generate_resource_file_content(
            "driver_pool_pipeline", self.generated_dir, "dev"
        )

        parsed = yaml.safe_load(content)
        cluster = parsed["resources"]["pipelines"]["driver_pool_pipeline_pipeline"][
            "clusters"
        ][0]

        assert cluster["instance_pool_id"] == "worker-pool-123"
        assert cluster["driver_instance_pool_id"] == "driver-pool-456"
        assert "node_type_id" not in cluster

    def test_instance_pool_with_token_substitution(self):
        """Should resolve tokenized pool IDs through substitution."""
        config_file = self.project_root / "config" / "pipeline_config.yaml"
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.write_text("""
---
pipeline: token_pool_test
catalog: test_catalog
schema: test_schema
serverless: false
clusters:
  - label: default
    instance_pool_id: "${worker_pool_id}"
    driver_instance_pool_id: "${driver_pool_id}"
    autoscale:
      min_workers: 1
      max_workers: 5
""")

        sub_file = self.project_root / "substitutions" / "dev.yaml"
        sub_file.parent.mkdir(parents=True, exist_ok=True)
        sub_file.write_text("""
dev:
  worker_pool_id: resolved-worker-pool-789
  driver_pool_id: resolved-driver-pool-012
""")

        manager = BundleManager(self.project_root, str(config_file))

        captured_context = None
        original_render = manager.template_renderer.render_template

        def mock_render(template_name, context):
            nonlocal captured_context
            captured_context = context
            return original_render(template_name, context)

        manager.template_renderer.render_template = mock_render

        try:
            content = manager.generate_resource_file_content(
                "token_pool_test", self.generated_dir, "dev"
            )

            assert captured_context is not None
            cluster = captured_context["pipeline_config"]["clusters"][0]
            assert cluster["instance_pool_id"] == "resolved-worker-pool-789"
            assert cluster["driver_instance_pool_id"] == "resolved-driver-pool-012"

            parsed = yaml.safe_load(content)
            rendered_cluster = parsed["resources"]["pipelines"][
                "token_pool_test_pipeline"
            ]["clusters"][0]
            assert rendered_cluster["instance_pool_id"] == "resolved-worker-pool-789"
            assert (
                rendered_cluster["driver_instance_pool_id"]
                == "resolved-driver-pool-012"
            )
        finally:
            manager.template_renderer.render_template = original_render


class TestBundleJinja2TemplateHelpers:
    def setup_method(self):
        self.temp_dir = Path(tempfile.mkdtemp())

    def teardown_method(self):
        shutil.rmtree(self.temp_dir)

    def test_template_file_discovery(self):
        """Should find and load bundle template files."""
        from pathlib import Path

        import lhp
        from lhp.bundle.manager import BundleManager

        manager = BundleManager(self.temp_dir)

        lhp_path = Path(lhp.__file__).parent
        bundle_template_dir = lhp_path / "templates" / "bundle"
        template_file = bundle_template_dir / "pipeline_resource.yml.j2"

        assert bundle_template_dir.exists(), (
            f"Bundle template directory not found: {bundle_template_dir}"
        )
        assert bundle_template_dir.is_dir(), (
            f"Bundle template path is not a directory: {bundle_template_dir}"
        )
        assert template_file.exists(), f"Template file not found: {template_file}"
        assert template_file.is_file(), f"Template path is not a file: {template_file}"

        try:
            content = template_file.read_text()
            assert len(content) > 0, "Template file should not be empty"
            assert "{{ pipeline_name }}" in content, (
                "Template should contain pipeline_name variable"
            )
            assert "resources:" in content, "Template should contain YAML structure"
            assert "pipelines:" in content, "Template should contain pipelines section"

        except Exception as e:
            pytest.fail(f"Could not read template file: {e}")

        try:
            template = manager.template_renderer.env.get_template(
                "bundle/pipeline_resource.yml.j2"
            )
            assert template is not None, (
                "Template should be loadable by Jinja2 environment"
            )

        except Exception as e:
            pytest.fail(f"Template could not be loaded by Jinja2: {e}")

    def test_template_variable_validation(self):
        """Should validate required template variables are present."""
        from pathlib import Path

        import lhp
        from lhp.bundle.manager import BundleManager

        manager = BundleManager(self.temp_dir)

        template = manager.template_renderer.env.get_template(
            "bundle/pipeline_resource.yml.j2"
        )

        lhp_path = Path(lhp.__file__).parent
        template_file = lhp_path / "templates" / "bundle" / "pipeline_resource.yml.j2"
        template_source = template_file.read_text()

        required_variables = [
            "pipeline_name",
        ]

        for var in required_variables:
            var_pattern = f"{{{{ {var} }}}}"
            assert var_pattern in template_source, (
                f"Template missing required variable: {var}"
            )

        default_pipeline_config = {
            "serverless": True,
            "edition": "ADVANCED",
            "channel": "CURRENT",
            "continuous": False,
        }
        valid_contexts = [
            {
                "pipeline_name": "test_pipeline",
                "pipeline_config": default_pipeline_config,
            },
            {
                "pipeline_name": "bronze_ingestion",
                "pipeline_config": default_pipeline_config,
            },
            {
                "pipeline_name": "complex_data_transformation",
                "pipeline_config": default_pipeline_config,
            },
        ]

        for context in valid_contexts:
            try:
                result = template.render(**context)
                assert result is not None
                assert len(result) > 0
                assert context["pipeline_name"] in result

            except Exception as e:
                pytest.fail(f"Template failed with valid context {context}: {e}")

        invalid_contexts = [
            {},
            {"wrong_variable": "test"},
            {"pipeline_name": None},
        ]

        for context in invalid_contexts:
            try:
                result = template.render(**context)
                if "pipeline_name" not in context or context["pipeline_name"] is None:
                    assert "{{ pipeline_name }}" in result or "None" in result

            except Exception:
                pass

        special_contexts = [
            {
                "pipeline_name": "test<script>alert('xss')</script>",
                "pipeline_config": default_pipeline_config,
            },
            {
                "pipeline_name": "test&special&chars",
                "pipeline_config": default_pipeline_config,
            },
            {
                "pipeline_name": 'test"quotes"',
                "pipeline_config": default_pipeline_config,
            },
        ]

        for context in special_contexts:
            try:
                result = template.render(**context)
                assert context["pipeline_name"] in result

            except Exception as e:
                pytest.fail(
                    f"Template failed with special characters context {context}: {e}"
                )
