"""Test suite for environment-specific directory structure changes."""

import os
import shutil
import tempfile
from pathlib import Path

import pytest
import yaml
from click.testing import CliRunner

from lhp.bundle.manager import BundleManager
from lhp.cli.main import cli


class TestEnvironmentDirectories:
    """Test environment-based directory structure."""

    def setup_method(self):
        self.temp_dir = Path(tempfile.mkdtemp())
        self.runner = CliRunner()

    def teardown_method(self):
        shutil.rmtree(self.temp_dir)

    def test_bundle_resources_created_in_environment_directory(self):
        """Verify bundle resources created in resources/lhp/{env}/."""
        project_root = self.temp_dir / "test_project"
        project_root.mkdir()

        (project_root / "databricks.yml").write_text("bundle:\n  name: test_bundle")

        generated_dir = project_root / "generated" / "dev"
        pipeline_dir = generated_dir / "test_pipeline"
        pipeline_dir.mkdir(parents=True)
        (pipeline_dir / "test.py").write_text("""
from pyspark import pipelines as dp

@dp.materialized_view(name="test_catalog.test_schema.test_table")
def test_table():
    pass
""")

        config_file = project_root / "pipeline_config.yaml"
        config_file.write_text(
            "project_defaults:\n  catalog: test_catalog\n  schema: test_schema\n"
        )

        manager = BundleManager(project_root, pipeline_config_path=str(config_file))
        manager.sync_resources_with_generated_files(generated_dir, "dev")

        resource_file = (
            project_root / "resources" / "lhp" / "test_pipeline.pipeline.yml"
        )
        assert resource_file.exists(), (
            "Resource file should be created in root directory"
        )

        content = resource_file.read_text()
        assert "Generated by LakehousePlumber" in content
        assert "test_pipeline" in content

    def test_pipeline_template_includes_environment_paths(self):
        """Verify pipeline.yml contains environment in paths."""
        project_root = self.temp_dir / "test_project"
        project_root.mkdir()

        generated_dir = project_root / "generated" / "staging"
        pipeline_dir = generated_dir / "data_pipeline"
        pipeline_dir.mkdir(parents=True)
        (pipeline_dir / "transform.py").write_text("""
from pyspark import pipelines as dp

dp.create_streaming_table(name="staging_catalog.staging_schema.staging_table")
""")

        config_file = project_root / "pipeline_config.yaml"
        config_file.write_text(
            "project_defaults:\n  catalog: staging_catalog\n  schema: staging_schema\n"
        )

        manager = BundleManager(project_root, pipeline_config_path=str(config_file))
        content = manager.generate_resource_file_content(
            "data_pipeline", generated_dir, "staging"
        )

        parsed = yaml.safe_load(content)
        pipeline_config = parsed["resources"]["pipelines"]["data_pipeline_pipeline"]

        libraries = pipeline_config["libraries"]
        assert len(libraries) == 1
        glob_include = libraries[0]["glob"]["include"]
        assert (
            glob_include
            == "${workspace.file_path}/generated/${bundle.target}/data_pipeline/**"
        )

        root_path = pipeline_config["root_path"]
        assert (
            root_path
            == "${workspace.file_path}/generated/${bundle.target}/data_pipeline"
        )

        source_path = pipeline_config["configuration"]["bundle.sourcePath"]
        assert source_path == "${workspace.file_path}/generated/${bundle.target}"

    def test_template_requires_env_parameter(self):
        """Verify templates require env parameter (breaking change)."""
        project_root = self.temp_dir / "template_test"
        project_root.mkdir()

        generated_dir = project_root / "generated"
        generated_dir.mkdir()

        config_file = project_root / "pipeline_config.yaml"
        config_file.write_text(
            "project_defaults:\n  catalog: test_catalog\n  schema: test_schema\n"
        )
        manager = BundleManager(project_root, pipeline_config_path=str(config_file))

        import pytest

        with pytest.raises(TypeError):
            content = manager.generate_resource_file_content(
                "test_pipeline", generated_dir
            )

        content = manager.generate_resource_file_content(
            "test_pipeline", generated_dir, "dev"
        )

        parsed = yaml.safe_load(content)
        assert parsed is not None
        assert "resources" in parsed

        lines = content.split("\n")
        header = lines[0]
        assert "(None)" not in header
        assert "Generated by LakehousePlumber" in header
