"""Tests for StateCleanupService."""

import pytest
from datetime import datetime
from pathlib import Path
from unittest.mock import patch

from lhp.core.state.state_cleanup_service import StateCleanupService
from lhp.core.state_models import FileState, ProjectState


def _make_file_state(
    generated_path,
    source_yaml,
    pipeline="bronze",
    flowgroup="flow",
    environment="dev",
):
    """Helper to create a FileState with required fields."""
    return FileState(
        generated_path=generated_path,
        source_yaml=source_yaml,
        checksum="abc123",
        source_yaml_checksum="def456",
        timestamp=datetime.now().isoformat(),
        environment=environment,
        pipeline=pipeline,
        flowgroup=flowgroup,
    )


class TestIsLhpGeneratedFile:
    """Tests for is_lhp_generated_file method."""

    def test_lhp_generated_file(self, tmp_path):
        """File containing 'Generated by LakehousePlumber' in first 5 lines returns True."""
        service = StateCleanupService(tmp_path)
        py_file = tmp_path / "test.py"
        py_file.write_text("# Generated by LakehousePlumber v0.7\nimport dlt\n")
        assert service.is_lhp_generated_file(py_file) is True

    def test_lhp_header_on_later_line_within_limit(self, tmp_path):
        """Header on line 4 (within first 5 lines) returns True."""
        service = StateCleanupService(tmp_path)
        py_file = tmp_path / "test.py"
        py_file.write_text(
            "# comment\n# comment\n# comment\n# Generated by LakehousePlumber\nimport dlt\n"
        )
        assert service.is_lhp_generated_file(py_file) is True

    def test_non_lhp_file(self, tmp_path):
        """File without LHP header returns False."""
        service = StateCleanupService(tmp_path)
        py_file = tmp_path / "test.py"
        py_file.write_text("import os\nprint('hello')\n")
        assert service.is_lhp_generated_file(py_file) is False

    def test_nonexistent_file(self, tmp_path):
        """Non-existent file returns False."""
        service = StateCleanupService(tmp_path)
        missing = tmp_path / "nonexistent.py"
        assert service.is_lhp_generated_file(missing) is False

    def test_non_py_file(self, tmp_path):
        """Non-.py file returns False even with LHP header."""
        service = StateCleanupService(tmp_path)
        txt_file = tmp_path / "test.txt"
        txt_file.write_text("# Generated by LakehousePlumber\n")
        assert service.is_lhp_generated_file(txt_file) is False

    def test_unreadable_binary_file(self, tmp_path):
        """Binary file that cannot be decoded as UTF-8 returns False."""
        service = StateCleanupService(tmp_path)
        bin_file = tmp_path / "binary.py"
        bin_file.write_bytes(b"\x80\x81\x82\x83\x84\x85\x86\x87\x88\x89")
        assert service.is_lhp_generated_file(bin_file) is False


class TestScanGeneratedDirectory:
    """Tests for scan_generated_directory method."""

    def test_scan_finds_py_files(self, tmp_path):
        """Directory with .py files returns set of relative paths."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        (gen_dir / "pipeline.py").write_text("# code")
        result = service.scan_generated_directory(gen_dir)
        assert len(result) == 1
        # Paths should be relative to project_root
        expected = Path("generated") / "dev" / "pipeline.py"
        assert expected in result

    def test_scan_finds_nested_py_files(self, tmp_path):
        """Recursively finds .py files in subdirectories."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        sub_dir = gen_dir / "bronze"
        sub_dir.mkdir(parents=True)
        (gen_dir / "top.py").write_text("# code")
        (sub_dir / "nested.py").write_text("# code")
        result = service.scan_generated_directory(gen_dir)
        assert len(result) == 2

    def test_scan_empty_directory(self, tmp_path):
        """Empty directory returns empty set."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        result = service.scan_generated_directory(gen_dir)
        assert result == set()

    def test_scan_nonexistent_directory(self, tmp_path):
        """Non-existent directory returns empty set."""
        service = StateCleanupService(tmp_path)
        missing_dir = tmp_path / "nonexistent"
        result = service.scan_generated_directory(missing_dir)
        assert result == set()

    def test_scan_ignores_non_py_files(self, tmp_path):
        """Non-.py files are excluded from results."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        (gen_dir / "pipeline.py").write_text("# code")
        (gen_dir / "readme.txt").write_text("readme")
        (gen_dir / "config.yaml").write_text("key: value")
        result = service.scan_generated_directory(gen_dir)
        assert len(result) == 1


class TestCleanupUntrackedFiles:
    """Tests for cleanup_untracked_files method."""

    def test_cleanup_removes_lhp_untracked(self, tmp_path):
        """Untracked LHP-generated file is removed."""
        service = StateCleanupService(tmp_path)
        # Create output dir with an untracked LHP file
        output_dir = tmp_path / "generated" / "dev"
        output_dir.mkdir(parents=True)
        untracked = output_dir / "old_pipeline.py"
        untracked.write_text("# Generated by LakehousePlumber\nimport dlt\n")

        # Empty state (nothing tracked)
        state = ProjectState(environments={"dev": {}})

        removed = service.cleanup_untracked_files(state, output_dir, "dev")
        assert len(removed) == 1
        assert not untracked.exists()

    def test_cleanup_skips_non_lhp_file(self, tmp_path):
        """Untracked non-LHP file is not removed."""
        service = StateCleanupService(tmp_path)
        output_dir = tmp_path / "generated" / "dev"
        output_dir.mkdir(parents=True)
        non_lhp = output_dir / "user_script.py"
        non_lhp.write_text("import os\nprint('user code')\n")

        state = ProjectState(environments={"dev": {}})

        removed = service.cleanup_untracked_files(state, output_dir, "dev")
        assert len(removed) == 0
        assert non_lhp.exists()

    def test_cleanup_skips_tracked_files(self, tmp_path):
        """All files tracked in state are left untouched."""
        service = StateCleanupService(tmp_path)
        output_dir = tmp_path / "generated" / "dev"
        output_dir.mkdir(parents=True)
        tracked_file = output_dir / "pipeline.py"
        tracked_file.write_text("# Generated by LakehousePlumber\nimport dlt\n")

        rel_path = str(Path("generated") / "dev" / "pipeline.py")
        file_state = _make_file_state(
            generated_path=rel_path,
            source_yaml="pipelines/bronze/flow.yaml",
        )
        state = ProjectState(environments={"dev": {rel_path: file_state}})

        removed = service.cleanup_untracked_files(state, output_dir, "dev")
        assert len(removed) == 0
        assert tracked_file.exists()

    def test_cleanup_mixed_tracked_and_untracked(self, tmp_path):
        """Only untracked LHP files are removed; tracked files and non-LHP files remain."""
        service = StateCleanupService(tmp_path)
        output_dir = tmp_path / "generated" / "dev"
        output_dir.mkdir(parents=True)

        # Tracked file
        tracked = output_dir / "tracked.py"
        tracked.write_text("# Generated by LakehousePlumber\nimport dlt\n")

        # Untracked LHP file
        untracked_lhp = output_dir / "orphan.py"
        untracked_lhp.write_text("# Generated by LakehousePlumber\nimport dlt\n")

        # Untracked non-LHP file
        untracked_non_lhp = output_dir / "manual.py"
        untracked_non_lhp.write_text("print('hello')\n")

        rel_tracked = str(Path("generated") / "dev" / "tracked.py")
        file_state = _make_file_state(
            generated_path=rel_tracked,
            source_yaml="pipelines/bronze/flow.yaml",
        )
        state = ProjectState(environments={"dev": {rel_tracked: file_state}})

        removed = service.cleanup_untracked_files(state, output_dir, "dev")
        assert len(removed) == 1
        assert tracked.exists()
        assert not untracked_lhp.exists()
        assert untracked_non_lhp.exists()


class TestCleanupOrphanedFiles:
    """Tests for cleanup_orphaned_files method."""

    def test_cleanup_orphaned_dry_run(self, tmp_path):
        """dry_run=True reports files but does not delete them."""
        service = StateCleanupService(tmp_path)
        # Create a generated file
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        gen_file = gen_dir / "pipeline.py"
        gen_file.write_text("# Generated by LakehousePlumber\n")

        # Create state tracking a file whose source YAML does not exist
        rel_gen_path = "generated/dev/pipeline.py"
        file_state = _make_file_state(
            generated_path=rel_gen_path,
            source_yaml="pipelines/bronze/flow.yaml",
            pipeline="bronze",
            flowgroup="flow",
        )
        state = ProjectState(
            environments={"dev": {rel_gen_path: file_state}}
        )

        deleted = service.cleanup_orphaned_files(state, "dev", dry_run=True)
        assert len(deleted) == 1
        # File should still exist (dry run)
        assert gen_file.exists()
        # State should not be modified in dry run
        assert rel_gen_path in state.environments["dev"]

    def test_cleanup_orphaned_dry_run_does_not_call_cleanup_empty_directories(
        self, tmp_path
    ):
        """Verify cleanup_empty_directories is NOT called in dry_run mode."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        gen_file = gen_dir / "pipeline.py"
        gen_file.write_text("# Generated by LakehousePlumber\n")

        rel_gen_path = "generated/dev/pipeline.py"
        file_state = _make_file_state(
            generated_path=rel_gen_path,
            source_yaml="pipelines/bronze/flow.yaml",
        )
        state = ProjectState(
            environments={"dev": {rel_gen_path: file_state}}
        )

        with patch.object(service, "cleanup_empty_directories") as mock_cleanup:
            service.cleanup_orphaned_files(state, "dev", dry_run=True)
            mock_cleanup.assert_not_called()

    def test_cleanup_orphaned_actual_delete(self, tmp_path):
        """Without dry_run, orphaned files are actually deleted and removed from state."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        gen_file = gen_dir / "pipeline.py"
        gen_file.write_text("# Generated by LakehousePlumber\n")

        rel_gen_path = "generated/dev/pipeline.py"
        file_state = _make_file_state(
            generated_path=rel_gen_path,
            source_yaml="pipelines/bronze/flow.yaml",
        )
        state = ProjectState(
            environments={"dev": {rel_gen_path: file_state}}
        )

        deleted = service.cleanup_orphaned_files(state, "dev", dry_run=False)
        assert len(deleted) == 1
        assert not gen_file.exists()
        # State entry should be removed
        assert rel_gen_path not in state.environments["dev"]

    def test_cleanup_orphaned_no_orphans(self, tmp_path):
        """When source YAML exists and flowgroup matches, no files are deleted."""
        service = StateCleanupService(tmp_path)
        gen_dir = tmp_path / "generated" / "dev"
        gen_dir.mkdir(parents=True)
        gen_file = gen_dir / "pipeline.py"
        gen_file.write_text("# Generated by LakehousePlumber\n")

        # Create a source YAML that exists
        pipelines_dir = tmp_path / "pipelines" / "bronze"
        pipelines_dir.mkdir(parents=True)
        source_yaml = pipelines_dir / "flow.yaml"
        source_yaml.write_text(
            "pipeline: bronze\nflowgroup: flow\nactions:\n  - name: test\n"
        )

        rel_gen_path = "generated/dev/pipeline.py"
        file_state = _make_file_state(
            generated_path=rel_gen_path,
            source_yaml="pipelines/bronze/flow.yaml",
            pipeline="bronze",
            flowgroup="flow",
        )
        state = ProjectState(
            environments={"dev": {rel_gen_path: file_state}}
        )

        deleted = service.cleanup_orphaned_files(state, "dev", dry_run=False)
        # Depending on whether the YAML parser can parse this file, it may or may not
        # find the flowgroup. But the source file exists, so at minimum we verify no
        # crash occurs.
        assert isinstance(deleted, list)
