"""Post-refactor BundleManager contract tests (some fail against current code).

Behavioral invariants under test:
* ``resources/lhp/`` is wiped and re-rendered on every ``lhp generate``.
* Catalog/schema MUST come from ``pipeline_config.yaml``. User-facing validation
  is in ``bundle.preflight.validate_catalog_schema`` (raises ``LHP-CFG-026``);
  the bundle-write phase keeps an internal guard that raises ``LHP-GEN-001``
  if preflight was bypassed.
* ``DatabricksYAMLManager`` is deleted; ``databricks.yml`` is never mutated.
* ``sync_resources_with_generated_files`` no longer accepts ``force`` or
  ``has_pipeline_config``.
"""

import hashlib
import inspect
from pathlib import Path

import pytest

from lhp.bundle.exceptions import BundleResourceError
from lhp.bundle.manager import BundleManager
from lhp.errors import LHPError

# ---------------------------------------------------------------------------
# Test helpers
# ---------------------------------------------------------------------------


def _write_pipeline_config_file(
    project_root: Path,
    *,
    project_defaults: dict | None = None,
    pipelines: dict[str, dict] | None = None,
) -> Path:
    docs: list[str] = []
    if project_defaults is not None:
        docs.append(_dict_to_doc({"project_defaults": project_defaults}))
    for name, cfg in (pipelines or {}).items():
        cfg_with_name = {"pipeline": name, **cfg}
        docs.append(_dict_to_doc(cfg_with_name))
    text = "\n---\n".join(docs) if docs else ""
    config_dir = project_root / "config"
    config_dir.mkdir(parents=True, exist_ok=True)
    config_path = config_dir / "pipeline_config.yaml"
    config_path.write_text(text, encoding="utf-8")
    return config_path


def _dict_to_doc(d: dict) -> str:
    import yaml

    return yaml.safe_dump(d, sort_keys=False)


def _write_substitution_file(project_root: Path, env: str) -> Path:
    """Write a minimal substitution file so the substitution loader doesn't fail."""
    subs_dir = project_root / "substitutions"
    subs_dir.mkdir(parents=True, exist_ok=True)
    sub_file = subs_dir / f"{env}.yaml"
    sub_file.write_text(f"{env}:\n  dummy: value\n", encoding="utf-8")
    return sub_file


def _make_pipeline_dirs(generated_dir: Path, names: list[str]) -> list[Path]:
    out = []
    for name in names:
        pdir = generated_dir / name
        pdir.mkdir(parents=True, exist_ok=True)
        (pdir / "__init__.py").write_text("", encoding="utf-8")
        out.append(pdir)
    return out


@pytest.mark.unit
def test_sync_writes_resource_file_for_every_current_pipeline(tmp_path):
    """Sync renders one resource YAML per pipeline directory; stale LHP files must be overwritten."""
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a", "pipeline_b"])
    _write_substitution_file(project_root, "dev")
    config_path = _write_pipeline_config_file(
        project_root,
        project_defaults={"catalog": "fresh_catalog", "schema": "fresh_schema"},
    )

    resources_dir = project_root / "resources" / "lhp"
    resources_dir.mkdir(parents=True, exist_ok=True)
    (resources_dir / "pipeline_a.pipeline.yml").write_text(
        "# Generated by LakehousePlumber - stale content\n"
        "resources:\n"
        "  pipelines:\n"
        "    pipeline_a_pipeline:\n"
        "      name: pipeline_a_pipeline\n"
        "      catalog: STALE_CATALOG\n"
        "      schema: STALE_SCHEMA\n",
        encoding="utf-8",
    )

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))
    manager.sync_resources_with_generated_files(generated_root, "dev")

    rendered = sorted(p.name for p in resources_dir.glob("*.pipeline.yml"))
    assert rendered == ["pipeline_a.pipeline.yml", "pipeline_b.pipeline.yml"]

    pipeline_a_content = (resources_dir / "pipeline_a.pipeline.yml").read_text()
    assert "STALE_CATALOG" not in pipeline_a_content
    assert "fresh_catalog" in pipeline_a_content


@pytest.mark.unit
def test_sync_signature_drops_force_and_has_pipeline_config():
    """Post-refactor signature must not expose force / has_pipeline_config."""
    params = inspect.signature(
        BundleManager.sync_resources_with_generated_files
    ).parameters
    assert "force" not in params
    assert "has_pipeline_config" not in params


@pytest.mark.unit
def test_missing_catalog_and_schema_raises_config_error(tmp_path):
    """Direct call bypasses preflight → internal guard fires (``LHP-GEN-001``).

    User-facing validation is ``LHP-CFG-026`` via ``bundle.preflight.validate_catalog_schema``.
    ``LHP-GEN-001`` is the guard for non-CLI callers that skip preflight.
    """
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a"])
    _write_substitution_file(project_root, "dev")
    config_path = _write_pipeline_config_file(
        project_root,
        project_defaults={"serverless": True},  # intentionally missing catalog/schema
        pipelines={"pipeline_a": {"serverless": True}},
    )

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))

    with pytest.raises(LHPError) as exc_info:
        manager.generate_resource_file_content("pipeline_a", generated_root, "dev")

    assert exc_info.value.code == "LHP-GEN-001"
    assert "preflight" in str(exc_info.value).lower()


@pytest.mark.unit
def test_per_pipeline_catalog_schema_resolves(tmp_path):
    """Per-pipeline catalog/schema render literally in the regenerated YAML."""
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a"])
    _write_substitution_file(project_root, "dev")
    config_path = _write_pipeline_config_file(
        project_root,
        pipelines={
            "pipeline_a": {
                "catalog": "specific_catalog",
                "schema": "specific_schema",
            }
        },
    )

    resources_dir = project_root / "resources" / "lhp"
    resources_dir.mkdir(parents=True, exist_ok=True)
    (resources_dir / "pipeline_a.pipeline.yml").write_text(
        "# Generated by LakehousePlumber - stale\n"
        "resources:\n"
        "  pipelines:\n"
        "    pipeline_a_pipeline:\n"
        "      name: pipeline_a_pipeline\n"
        "      catalog: OLD_CATALOG\n"
        "      schema: OLD_SCHEMA\n",
        encoding="utf-8",
    )

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))
    manager.sync_resources_with_generated_files(generated_root, "dev")

    content = (resources_dir / "pipeline_a.pipeline.yml").read_text()
    assert "specific_catalog" in content
    assert "specific_schema" in content
    assert "OLD_CATALOG" not in content


@pytest.mark.unit
def test_project_defaults_catalog_schema_resolves(tmp_path):
    """project_defaults catalog/schema flows through when no per-pipeline override."""
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a"])
    _write_substitution_file(project_root, "dev")
    config_path = _write_pipeline_config_file(
        project_root,
        project_defaults={
            "catalog": "defaults_catalog",
            "schema": "defaults_schema",
        },
    )

    resources_dir = project_root / "resources" / "lhp"
    resources_dir.mkdir(parents=True, exist_ok=True)
    (resources_dir / "pipeline_a.pipeline.yml").write_text(
        "# Generated by LakehousePlumber - stale\n"
        "resources:\n"
        "  pipelines:\n"
        "    pipeline_a_pipeline:\n"
        "      name: pipeline_a_pipeline\n"
        "      catalog: OLD_CATALOG\n"
        "      schema: OLD_SCHEMA\n",
        encoding="utf-8",
    )

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))
    manager.sync_resources_with_generated_files(generated_root, "dev")

    content = (resources_dir / "pipeline_a.pipeline.yml").read_text()
    assert "defaults_catalog" in content
    assert "defaults_schema" in content
    assert "OLD_CATALOG" not in content


@pytest.mark.unit
def test_per_pipeline_overrides_project_defaults(tmp_path):
    """Both blocks present -> per-pipeline values win over project_defaults."""
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a"])
    _write_substitution_file(project_root, "dev")
    config_path = _write_pipeline_config_file(
        project_root,
        project_defaults={
            "catalog": "defaults_catalog",
            "schema": "defaults_schema",
        },
        pipelines={
            "pipeline_a": {
                "catalog": "override_catalog",
                "schema": "override_schema",
            }
        },
    )

    resources_dir = project_root / "resources" / "lhp"
    resources_dir.mkdir(parents=True, exist_ok=True)
    (resources_dir / "pipeline_a.pipeline.yml").write_text(
        "# Generated by LakehousePlumber - stale\n"
        "resources:\n"
        "  pipelines:\n"
        "    pipeline_a_pipeline:\n"
        "      name: pipeline_a_pipeline\n"
        "      catalog: STALE\n"
        "      schema: STALE\n",
        encoding="utf-8",
    )

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))
    manager.sync_resources_with_generated_files(generated_root, "dev")

    content = (resources_dir / "pipeline_a.pipeline.yml").read_text()
    assert "override_catalog" in content
    assert "override_schema" in content
    assert "defaults_catalog" not in content
    assert "defaults_schema" not in content
    assert "STALE" not in content


@pytest.mark.unit
def test_incomplete_catalog_pairing_raises_config_error(tmp_path):
    """catalog without schema → internal-error guard ``LHP-GEN-001``."""
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a"])
    _write_substitution_file(project_root, "dev")
    config_path = _write_pipeline_config_file(
        project_root,
        pipelines={"pipeline_a": {"catalog": "lonely_catalog"}},
    )

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))

    with pytest.raises(LHPError) as exc_info:
        manager.generate_resource_file_content("pipeline_a", generated_root, "dev")

    assert exc_info.value.code == "LHP-GEN-001"
    assert "preflight" in str(exc_info.value).lower()


@pytest.mark.unit
def test_bundle_manager_does_not_mutate_databricks_yml(tmp_path):
    """databricks.yml must be byte-identical before and after a sync."""
    project_root = tmp_path
    generated_root = project_root / "generated" / "dev"
    _make_pipeline_dirs(generated_root, ["pipeline_a"])
    _write_substitution_file(project_root, "dev")

    config_path = _write_pipeline_config_file(
        project_root,
        project_defaults={
            "catalog": "valid_catalog",
            "schema": "valid_schema",
            "serverless": True,
        },
    )

    databricks_yml = project_root / "databricks.yml"
    original_contents = (
        "bundle:\n"
        "  name: example_bundle\n"
        "\n"
        "targets:\n"
        "  dev:\n"
        "    variables:\n"
        "      my_custom_var: hand_authored_value\n"
        "      another_var: please_do_not_touch\n"
    )
    databricks_yml.write_text(original_contents, encoding="utf-8")
    pre_hash = hashlib.sha256(databricks_yml.read_bytes()).hexdigest()

    manager = BundleManager(project_root, str(config_path.relative_to(project_root)))
    manager.sync_resources_with_generated_files(generated_root, "dev")

    post_hash = hashlib.sha256(databricks_yml.read_bytes()).hexdigest()
    assert pre_hash == post_hash, (
        "databricks.yml was mutated by sync; it must remain untouched."
    )


@pytest.mark.unit
def test_databricks_yaml_manager_module_removed():
    """The DatabricksYAMLManager module/class no longer exists after refactor."""
    with pytest.raises(ImportError):
        from lhp.bundle.databricks_yaml_manager import (
            DatabricksYAMLManager,
        )
