"""
End-to-end integration tests for complete bundle workflow.

Tests the entire bundle integration from project initialization through
generation and synchronization, using real project data and scenarios.
"""

import os
import shutil
import tempfile
from pathlib import Path

import pytest

from lhp.api import LakehousePlumberApplicationFacade, collect_response
from lhp.bundle.detection import should_enable_bundle_support
from lhp.bundle.manager import BundleManager
from lhp.cli.main import cli


class TestEndToEndBundleWorkflow:
    """Test complete bundle workflow from initialization to generation."""

    def setup_method(self):
        """Set up test environment for each test."""
        self.temp_dir = Path(tempfile.mkdtemp())
        self.project_root = self.temp_dir / "e2e_test_project"
        self.original_cwd = os.getcwd()

    def teardown_method(self):
        """Clean up test environment after each test."""
        os.chdir(self.original_cwd)
        shutil.rmtree(self.temp_dir)

    def test_bundle_workflow_with_multiple_environments(self):
        """Test bundle workflow across multiple environments."""
        self._setup_bundle_project()

        environments = ["dev", "test", "prod"]

        facade = LakehousePlumberApplicationFacade.for_project(
            self.project_root, enforce_version=False
        )

        for env in environments:
            # Generate for each environment
            output_dir = self.project_root / "generated"
            batch = collect_response(
                facade.generation.generate_pipelines(
                    pipeline_filter="test_pipeline",
                    env=env,
                    output_dir=output_dir,
                )
            )
            generated_files = batch.pipeline_responses[
                "test_pipeline"
            ].generated_filenames

            assert len(generated_files) > 0

            # Verify environment-specific content
            pipeline_dir = output_dir / "test_pipeline"
            if pipeline_dir.exists():
                generated_file = pipeline_dir / generated_files[0]
                if generated_file.exists():
                    content = generated_file.read_text()
                    # Should contain environment-specific substitutions
                    assert env in content.lower() or "catalog" in content.lower()

    def test_bundle_sync_with_actual_yaml_files(self):
        """Test bundle sync with real YAML resource files."""
        self._setup_bundle_project()

        # Create user's custom resource file (should be preserved - outside resources/lhp/)
        resources_dir = self.project_root / "resources"
        resources_dir.mkdir(exist_ok=True)

        user_resource_file = resources_dir / "user_custom_pipeline.yml"
        user_resource_file.write_text("""
resources:
  pipelines:
    user_custom_pipeline:
      clusters:
        - driver:
            "spark.databricks.cluster.profile": "singleNode"
          spark:
            spark.master: "local[*]"
      libraries:
        - notebook:
            path: ../src/custom_notebook.py
""")

        # Generate new files
        generated_dir = self.project_root / "generated" / "dev"
        pipeline_dir = generated_dir / "test_pipeline"
        pipeline_dir.mkdir(parents=True)
        (pipeline_dir / "new_notebook.py").write_text("# New test notebook")
        (pipeline_dir / "existing_notebook.py").write_text("# Existing notebook")

        # Pipeline config with catalog/schema (required after refactor)
        config_file = self.project_root / "pipeline_config.yaml"
        config_file.write_text(
            "project_defaults:\n  catalog: test_catalog\n  schema: test_schema\n"
        )

        # Test sync
        bundle_manager = BundleManager(
            self.project_root, pipeline_config_path=str(config_file)
        )
        updated_count = bundle_manager.sync_resources_with_generated_files(
            generated_dir, "dev"
        )

        # Verify sync worked
        assert updated_count >= 0  # Should not fail

        # Verify user's custom file was preserved and unchanged
        user_content = user_resource_file.read_text()
        assert "user_custom_pipeline" in user_content
        assert "../src/custom_notebook.py" in user_content

        # Verify LHP created its own file at root level (new behavior)
        lhp_resource_file = (
            self.project_root / "resources" / "lhp" / "test_pipeline.pipeline.yml"
        )
        assert lhp_resource_file.exists()

        lhp_content = lhp_resource_file.read_text()
        assert "Generated by LakehousePlumber" in lhp_content
        # Should use glob pattern with bundle variables (new behavior)
        assert "- glob:" in lhp_content
        assert (
            "include: ${workspace.file_path}/generated/${bundle.target}/test_pipeline/**"
            in lhp_content
        )

    def test_bundle_workflow_multiple_pipelines(self):
        """Verify bundle-enabled generation succeeds across multiple pipelines."""
        self._setup_bundle_project()

        # Create multiple pipelines
        pipelines_dir = self.project_root / "pipelines"
        for i in range(5):
            pipeline_file = pipelines_dir / f"pipeline_{i}.yaml"
            pipeline_file.write_text(f"""
pipeline: pipeline_{i}
flowgroup: flowgroup_{i}
actions:
  - name: load_{i}
    type: load
    source:
      type: delta
      database: "{{catalog}}.raw"
      table: table_{i}
    target: v_table_{i}
  - name: write_{i}
    type: write
    source: v_table_{i}
    write_target:
      type: streaming_table
      database: "{{catalog}}.bronze"
      table: table_{i}
""")

        facade = LakehousePlumberApplicationFacade.for_project(
            self.project_root, enforce_version=False
        )

        # Generate each pipeline; real perf coverage lives in tests/performance/
        for i in range(5):
            output_dir = self.project_root / "generated"
            batch = collect_response(
                facade.generation.generate_pipelines(
                    pipeline_filter=f"pipeline_{i}",
                    env="dev",
                    output_dir=output_dir,
                )
            )
            generated_files = batch.pipeline_responses[
                f"pipeline_{i}"
            ].generated_filenames
            assert len(generated_files) > 0

    def test_bundle_workflow_with_errors_and_recovery(self):
        """Test complete workflow handles errors gracefully."""
        self._setup_bundle_project()

        # Create scenario with some invalid YAML
        resources_dir = self.project_root / "resources"
        resources_dir.mkdir(exist_ok=True)

        # Valid resource file
        valid_file = resources_dir / "valid_pipeline.yml"
        valid_file.write_text("""
resources:
  pipelines:
    valid_pipeline:
      libraries: []
""")

        # Invalid resource file
        invalid_file = resources_dir / "invalid_pipeline.yml"
        invalid_file.write_text("""
resources:
  pipelines:
    invalid_pipeline:
      libraries: [invalid yaml structure
""")

        # Create corresponding generated files
        generated_dir = self.project_root / "generated" / "dev"

        valid_pipeline_dir = generated_dir / "valid_pipeline"
        valid_pipeline_dir.mkdir(parents=True)
        (valid_pipeline_dir / "valid.py").write_text("# Valid notebook")

        invalid_pipeline_dir = generated_dir / "invalid_pipeline"
        invalid_pipeline_dir.mkdir(parents=True)
        (invalid_pipeline_dir / "invalid.py").write_text("# Invalid notebook")

        # Test sync with mixed valid/invalid files
        bundle_manager = BundleManager(self.project_root)

        # Should not crash despite invalid YAML
        try:
            updated_count = bundle_manager.sync_resources_with_generated_files(
                generated_dir, "dev"
            )
            # Should return some count (possibly 0 due to errors, but not crash)
            assert isinstance(updated_count, int)
        except Exception as e:
            # If it raises an exception, it should be a controlled LHP exception:
            # BundleResourceError for bundle-internal failures, or LHPConfigError
            # if preflight is bypassed (LHP-GEN-001 internal-error guard).
            # User-facing catalog/schema validation is in
            # ``bundle.preflight.validate_catalog_schema`` (LHP-CFG-026).
            from lhp.bundle.exceptions import BundleResourceError
            from lhp.errors import LHPError

            assert isinstance(e, (BundleResourceError, LHPError))

    def test_mixed_bundle_and_non_bundle_projects(self):
        """Test that bundle and non-bundle projects can coexist."""
        # Create bundle project
        bundle_project = self.temp_dir / "bundle_project"
        bundle_project.mkdir()
        (bundle_project / "databricks.yml").write_text("bundle:\n  name: test")

        # Create non-bundle project
        non_bundle_project = self.temp_dir / "non_bundle_project"
        non_bundle_project.mkdir()

        # Test bundle detection
        assert should_enable_bundle_support(bundle_project)
        assert not should_enable_bundle_support(non_bundle_project)

        # Both should work with the facade
        for project_root in [bundle_project, non_bundle_project]:
            self._create_minimal_project_structure(project_root)
            facade = LakehousePlumberApplicationFacade.for_project(
                project_root, enforce_version=False
            )

            # Should initialize without errors; ``project_root`` is preserved
            # on the facade-built orchestrator (per the D4-prep inventory).
            assert facade._orchestrator.project_root == project_root

    def test_cli_integration_with_verbose_output(self):
        """Test CLI integration with verbose bundle output."""
        self._setup_bundle_project()

        # v0.8.7: bundle-enabled generate requires --pipeline-config.
        (self.project_root / "config").mkdir(parents=True, exist_ok=True)
        (self.project_root / "config" / "pipeline_config.yaml").write_text(
            "project_defaults:\n"
            "  catalog: test_catalog_dev\n"
            "  schema: bronze\n"
            "  serverless: true\n"
        )

        os.chdir(self.project_root)

        from click.testing import CliRunner

        runner = CliRunner()

        # Test verbose generation with bundle
        result = runner.invoke(
            cli,
            [
                "--verbose",
                "generate",
                "--env",
                "dev",
                "--dry-run",
                "--pipeline-config",
                "config/pipeline_config.yaml",
            ],
        )

        # Behavioral contract here is the clean exit; rendered text is
        # not load-bearing (bundle activity surfaces via Live-panel phase
        # marker >250ms and ``logger.debug`` records only).
        assert result.exit_code == 0

    def _setup_bundle_project(self):
        """Set up a basic bundle project for testing."""
        self.project_root.mkdir(parents=True)

        # Create bundle file with targets (required for new variable logic)
        (self.project_root / "databricks.yml").write_text("""
bundle:
  name: test_bundle

include:
  - resources/*.yml
  - resources/lhp/*.yml

targets:
  dev:
    mode: development
    default: true
    workspace:
      host: test.databricks.com
""")

        # Create LHP project structure
        self._create_minimal_project_structure(self.project_root)

    def _create_minimal_project_structure(self, project_root: Path):
        """Create minimal LHP project structure."""
        # Project config
        (project_root / "lhp.yaml").write_text("""
name: test_project
version: "1.0"
""")

        # Substitutions (with environment structure for new variable logic)
        subs_dir = project_root / "substitutions"
        subs_dir.mkdir(exist_ok=True)
        (subs_dir / "dev.yaml").write_text("""
dev:
  catalog: test_catalog
  raw_schema: raw
  bronze_schema: bronze
""")
        (subs_dir / "test.yaml").write_text("""
test:
  catalog: test_catalog
  raw_schema: raw
  bronze_schema: bronze
""")
        (subs_dir / "prod.yaml").write_text("""
prod:
  catalog: prod_catalog
  raw_schema: raw
  bronze_schema: bronze
""")

        # Basic pipeline
        pipes_dir = project_root / "pipelines"
        pipes_dir.mkdir(exist_ok=True)
        (pipes_dir / "test_pipeline.yaml").write_text("""
pipeline: test_pipeline
flowgroup: test_flowgroup
actions:
  - name: test_load
    type: load
    source:
      type: delta
      database: "{catalog}.{raw_schema}"
      table: test_table
    target: v_test_table
  - name: test_write
    type: write
    source: v_test_table
    write_target:
      type: streaming_table
      database: "{catalog}.bronze"
      table: test_table
""")


class TestEndToEndACMIIntegration:
    """Test end-to-end integration using the real ACMI project."""

    def setup_method(self):
        """Set up test environment."""
        self.original_cwd = os.getcwd()
        # Use the actual ACMI project
        self.acmi_project = Path(__file__).parent.parent / "Example_Projects" / "acmi"

        if not self.acmi_project.exists():
            pytest.skip("ACMI project not available for integration testing")

    def teardown_method(self):
        """Clean up test environment."""
        os.chdir(self.original_cwd)

    def test_acmi_project_multiple_pipelines(self):
        """Test ACMI project with multiple pipeline generations."""
        os.chdir(self.acmi_project)

        # Skip version enforcement for integration tests
        facade = LakehousePlumberApplicationFacade.for_project(
            self.acmi_project, enforce_version=False
        )

        # Test multiple pipeline fields
        pipeline_fields = ["raw_ingestions", "bronze_load", "silver_load", "gold_load"]

        for pipeline_field in pipeline_fields:
            batch = collect_response(
                facade.generation.generate_pipelines(
                    pipeline_filter=pipeline_field,
                    env="dev",
                    output_dir=None,
                )
            )
            pipeline_response = batch.pipeline_responses.get(pipeline_field)
            generated_files = (
                pipeline_response.generated_filenames if pipeline_response else ()
            )

            # Dry-run (output_dir=None) writes nothing; only verify
            # that filenames were returned and end with .py.
            if len(generated_files) > 0:
                for filename in generated_files:
                    assert filename.endswith(".py")


class TestEndToEndCompatibility:
    """Test compatibility scenarios and edge cases."""

    def setup_method(self):
        """Set up test environment."""
        self.temp_dir = Path(tempfile.mkdtemp())
        self.original_cwd = os.getcwd()

    def teardown_method(self):
        """Clean up test environment."""
        os.chdir(self.original_cwd)
        shutil.rmtree(self.temp_dir)

    def test_bundle_detection_across_different_scenarios(self):
        """Test bundle detection in various project configurations."""
        scenarios = [
            # (has_databricks_yml, expected_result, description)
            (True, True, "Standard bundle project"),
            (False, False, "Non-bundle project"),
        ]

        for has_bundle_file, expected, description in scenarios:
            project_dir = self.temp_dir / f"test_{has_bundle_file}"
            project_dir.mkdir()

            if has_bundle_file:
                (project_dir / "databricks.yml").write_text("bundle:\n  name: test")

            result = should_enable_bundle_support(project_dir)
            assert result == expected, f"Failed for scenario: {description}"

    def test_bundle_with_complex_project_structures(self):
        """Test bundle functionality with complex project structures."""
        project_root = self.temp_dir / "complex_project"
        project_root.mkdir()

        # Create bundle file
        (project_root / "databricks.yml").write_text("""
bundle:
  name: complex_project
  environments:
    dev:
      default: true
""")

        # Create complex LHP structure
        (project_root / "lhp.yaml").write_text("""
name: complex_project
version: "2.0"
include:
  - "pipelines/**/*.yaml"
""")

        # Nested pipeline structure
        nested_dir = project_root / "pipelines" / "data_sources" / "external"
        nested_dir.mkdir(parents=True)
        (nested_dir / "external_data.yaml").write_text("""
pipeline: external_sources
flowgroup: external_data_load
actions:
  - name: load_external
    type: load
    source:
      type: cloudfiles
      path: "/external/data/*.json"
      format: json
    target: v_external_raw
""")

        # Test bundle detection and basic functionality
        assert should_enable_bundle_support(project_root)

        # Test facade initialization; ``project_root`` is preserved on the
        # facade-built orchestrator (per the D4-prep inventory).
        facade = LakehousePlumberApplicationFacade.for_project(
            project_root, enforce_version=False
        )
        assert facade._orchestrator.project_root == project_root

    def test_repeated_generation_succeeds(self):
        """Run 15 generation iterations and verify each returns non-empty filenames."""
        project_root = self.temp_dir / "memory_test"
        project_root.mkdir()

        # Create bundle project
        (project_root / "databricks.yml").write_text("bundle:\n  name: memory_test")
        (project_root / "lhp.yaml").write_text("name: memory_test\nversion: '1.0'")

        # Create substitutions
        subs_dir = project_root / "substitutions"
        subs_dir.mkdir()
        (subs_dir / "dev.yaml").write_text("dev:\n  catalog: test")

        # Create many small pipelines to stress test
        pipes_dir = project_root / "pipelines"
        pipes_dir.mkdir()

        for i in range(20):
            (pipes_dir / f"pipeline_{i:02d}.yaml").write_text(f"""
pipeline: pipeline_{i:02d}
flowgroup: flowgroup_{i:02d}
actions:
  - name: load_{i:02d}
    type: load
    source:
      type: delta
      database: "{{catalog}}.raw"
      table: table_{i:02d}
    target: v_table_{i:02d}
  - name: write_{i:02d}
    type: write
    source: v_table_{i:02d}
    write_target:
      type: streaming_table
      database: "{{catalog}}.bronze"
      table: table_{i:02d}
""")

        facade = LakehousePlumberApplicationFacade.for_project(
            project_root, enforce_version=False
        )

        # Generate multiple times to test for memory leaks
        for iteration in range(3):
            for i in range(5):  # Test subset to keep test time reasonable
                batch = collect_response(
                    facade.generation.generate_pipelines(
                        pipeline_filter=f"pipeline_{i:02d}",
                        env="dev",
                        output_dir=None,
                    )
                )
                pipeline_response = batch.pipeline_responses.get(f"pipeline_{i:02d}")
                generated_files = (
                    pipeline_response.generated_filenames if pipeline_response else ()
                )
                assert len(generated_files) > 0

                # Clear reference to help garbage collection
                del generated_files

    def test_bundle_with_unicode_and_special_characters(self):
        """Test bundle functionality with Unicode and special characters."""
        project_root = self.temp_dir / "unicode_测试"
        project_root.mkdir()

        # Create bundle with Unicode content
        (project_root / "databricks.yml").write_text(
            """
bundle:
  name: unicode_测试_project
""",
            encoding="utf-8",
        )

        # Create LHP project with Unicode
        (project_root / "lhp.yaml").write_text(
            """
name: unicode_测试_project
version: "1.0"
""",
            encoding="utf-8",
        )

        # Test bundle detection
        assert should_enable_bundle_support(project_root)

        # Test bundle manager
        bundle_manager = BundleManager(project_root)

        # Should handle Unicode paths without errors
        assert bundle_manager.project_root == project_root
        assert bundle_manager.resources_dir.name == "lhp"
        assert bundle_manager.resources_dir.parent.name == "resources"
