# Generated by LakehousePlumber
# Pipeline: uc_tagging_core
# FlowGroup: uc_tag_noschema

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "uc_tagging_core"
FLOWGROUP_ID = "uc_tag_noschema"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_uc_region():
    """Delta source: acme_edw_dev.edw_raw.region_raw"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.region_raw")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.uc_region", comment="Streaming table: uc_region"
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.uc_region",
    name="f_region",
    comment="Append flow to acme_edw_dev.edw_bronze.uc_region",
)
def f_region():
    """Append flow to acme_edw_dev.edw_bronze.uc_region"""
    # Streaming flow
    df = spark.readStream.table("v_uc_region")

    return df
