# Generated by LakehousePlumber
# Pipeline: acmi_edw_raw
# FlowGroup: flowgroup_template_preset

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_raw"
FLOWGROUP_ID = "flowgroup_template_preset"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_precedence_test_raw():
    """Load data from <built-in function format> files at /data/precedence_test/*.csv"""
    df = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "csv")
        .option("cloudFiles.inferColumnTypes", "true")
        .option("cloudFiles.rescuedDataColumn", "_rescued_data")
        .option("ignoreCorruptFiles", "true")
        .option("ignoreMissingFiles", "true")
        .option("cloudFiles.useStrictGlobber", "false")
        .option("cloudFiles.maxFilesPerTrigger", 200)
        .load("/data/precedence_test/*.csv")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_raw.precedence_test_test",
    comment="Streaming table: precedence_test_test",
    table_properties={
        "delta.enableRowTracking": "true",
        "delta.autoOptimize.optimizeWrite": "true",
        "delta.enableChangeDataFeed": "true",
    },
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_raw.precedence_test_test",
    name="f_precedence_test",
    comment="Append flow to acme_edw_dev.edw_raw.precedence_test_test",
)
def f_precedence_test():
    """Append flow to acme_edw_dev.edw_raw.precedence_test_test"""
    # Streaming flow
    df = spark.readStream.table("v_precedence_test_raw")

    return df
