# Generated by LakehousePlumber
# Pipeline: acmi_edw_raw
# FlowGroup: nested_options_merge

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_raw"
FLOWGROUP_ID = "nested_options_merge"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_nested_raw():
    """Load data from <built-in function format> files at /data/nested/*.parquet"""
    df = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "parquet")
        .option("cloudFiles.schemaLocation", "/schemas/nested")
        .option("cloudFiles.rescuedDataColumn", "_rescued_data")
        .option("ignoreCorruptFiles", "true")
        .option("ignoreMissingFiles", "true")
        .option("cloudFiles.useStrictGlobber", "false")
        .option("cloudFiles.maxFilesPerTrigger", 200)
        .load("/data/nested/*.parquet")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_raw.nested_test", comment="Streaming table: nested_test"
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_raw.nested_test",
    name="f_nested_test",
    comment="Append flow to acme_edw_dev.edw_raw.nested_test",
)
def f_nested_test():
    """Append flow to acme_edw_dev.edw_raw.nested_test"""
    # Streaming flow
    df = spark.readStream.table("v_nested_raw")

    return df
