# Generated by LakehousePlumber
# Pipeline: acmi_edw_raw
# FlowGroup: source_schema_load

from pyspark import pipelines as dp
from pyspark.sql.types import (
    StructType,
    StructField,
    StringType,
    LongType,
    IntegerType,
    DoubleType,
    FloatType,
    BooleanType,
    DateType,
    TimestampType,
    DecimalType,
    BinaryType,
    ByteType,
    ShortType,
)

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_raw"
FLOWGROUP_ID = "source_schema_load"


# ============================================================================
# SOURCE VIEWS
# ============================================================================

# Define schema
customer_schema = StructType(
    [
        StructField(
            "c_custkey",
            LongType(),
            False,
            {"comment": "Customer key - primary identifier"},
        ),
        StructField("c_name", StringType(), False, {"comment": "Customer name"}),
        StructField("c_address", StringType(), True, {"comment": "Customer address"}),
        StructField(
            "c_nationkey",
            LongType(),
            False,
            {"comment": "Nation key - foreign key to nation"},
        ),
        StructField(
            "c_phone", StringType(), True, {"comment": "Customer phone number"}
        ),
        StructField(
            "c_acctbal", DecimalType(18, 2), True, {"comment": "Account balance"}
        ),
        StructField("c_mktsegment", StringType(), True, {"comment": "Market segment"}),
        StructField("c_comment", StringType(), True, {"comment": "Free-form comment"}),
        StructField(
            "last_modified_dt", TimestampType(), True, {"comment": "Last modified date"}
        ),
    ]
)


@dp.temporary_view()
def v_customer_schema_raw():
    """Load customer CSV with explicit schema enforcement"""
    df = (
        spark.readStream.format("cloudFiles")
        .schema(customer_schema)
        .option("cloudFiles.format", "csv")
        .load("/data/schema_test/*.csv")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_raw.customer_schema_test",
    comment="Streaming table: customer_schema_test",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_raw.customer_schema_test",
    name="f_customer_schema",
    comment="Append flow to acme_edw_dev.edw_raw.customer_schema_test",
)
def f_customer_schema():
    """Append flow to acme_edw_dev.edw_raw.customer_schema_test"""
    # Streaming flow
    df = spark.readStream.table("v_customer_schema_raw")

    return df
