# Generated by LakehousePlumber
# Pipeline: acmi_edw_raw
# FlowGroup: template_preset_merge

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_raw"
FLOWGROUP_ID = "template_preset_merge"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_merge_test_raw():
    """Load data from <built-in function format> files at /data/merge_test/*.csv"""
    df = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "csv")
        .option("cloudFiles.inferColumnTypes", "true")
        .option("cloudFiles.rescuedDataColumn", "_rescued_data")
        .option("ignoreCorruptFiles", "true")
        .option("ignoreMissingFiles", "true")
        .option("cloudFiles.useStrictGlobber", "false")
        .option("cloudFiles.maxFilesPerTrigger", 200)
        .load("/data/merge_test/*.csv")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_raw.merge_test_test",
    comment="Streaming table: merge_test_test",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_raw.merge_test_test",
    name="f_merge_test",
    comment="Append flow to acme_edw_dev.edw_raw.merge_test_test",
)
def f_merge_test():
    """Append flow to acme_edw_dev.edw_raw.merge_test_test"""
    # Streaming flow
    df = spark.readStream.table("v_merge_test_raw")

    return df
