# Generated by LakehousePlumber
# Pipeline: acmi_edw_raw
# FlowGroup: write_target_preset

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_raw"
FLOWGROUP_ID = "write_target_preset"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_write_preset_raw():
    """Load data from <built-in function format> files at /data/write_preset/*.csv"""
    df = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "csv")
        .load("/data/write_preset/*.csv")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_raw.write_preset_test",
    comment="Streaming table: write_preset_test",
    table_properties={
        "PII": "true",
        "delta.enableRowTracking": "true",
        "delta.autoOptimize.optimizeWrite": "true",
        "delta.enableChangeDataFeed": "true",
    },
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_raw.write_preset_test",
    name="f_with_preset_props",
    comment="Append flow to acme_edw_dev.edw_raw.write_preset_test",
)
def f_with_preset_props():
    """Append flow to acme_edw_dev.edw_raw.write_preset_test"""
    # Streaming flow
    df = spark.readStream.table("v_write_preset_raw")

    return df
