# LHP-SOURCE: py_functions/dep_bindings_union_transform.py
# Generated by LakehousePlumber - DO NOT EDIT
# Changes will be overwritten on next generation


def __lhp_sandbox_table(__lhp_ref):
    """Rewrite an in-scope produced-table reference to its sandbox name.

    Generated by Lakehouse Plumber for a ``--sandbox`` run. Mirrors the static
    matcher exactly: canonicalize the input (lowercase, strip backticks and
    whitespace per dotted part), match the produced set (3-part exact, then the
    2<->3-part short-key rule with the catalog-uniqueness guard), and on a match
    rename the LEAF of the caller's ORIGINAL spelling (preserving casing and
    backticks on every other part). No match returns the input unchanged
    (read-shared semantics); an already-renamed leaf no longer matches, so the
    rewrite is idempotent.
    """
    __lhp_produced = {
        "acme_edw_dev.edw_analytics.daily_order_metrics",
        "acme_edw_dev.edw_bronze.custom_api_data",
        "acme_edw_dev.edw_bronze.customers",
        "acme_edw_dev.edw_bronze.customers_clustered",
        "acme_edw_dev.edw_bronze.customers_clustered_with_row_filter",
        "acme_edw_dev.edw_bronze.customers_partitioned",
        "acme_edw_dev.edw_bronze.helper_enriched",
        "acme_edw_dev.edw_bronze.helper_loaded",
        "acme_edw_dev.edw_bronze.helper_snapshot_dim",
        "acme_edw_dev.edw_bronze.helper_source_data",
        "acme_edw_dev.edw_bronze.python_load_customers",
        "acme_edw_dev.edw_bronze.site_alpha_customer",
        "acme_edw_dev.edw_bronze.site_beta_customer",
        "acme_edw_dev.edw_gold.partsupp_modelled_fct",
        "acme_edw_dev.edw_silver.cdf_probe_out",
        "acme_edw_dev.edw_silver.configured_union",
        "acme_edw_dev.edw_silver.customer_dim",
        "acme_edw_dev.edw_silver.dim_sfcc_cust",
        "acme_edw_dev.edw_silver.nation_dim",
        "acme_edw_dev.edw_silver.opaque_read_out",
        "acme_edw_dev.edw_silver.param_snapshot_dim",
        "acme_edw_dev.edw_silver.partsupp_dim",
        "acme_edw_dev.edw_silver.site_alpha_customer_dim",
        "acme_edw_dev.edw_silver.site_beta_customer_dim",
        "acme_edw_dev.edw_silver.supplier_dim",
    }
    __lhp_short = {
        "edw_analytics.daily_order_metrics": ["acme_edw_dev"],
        "edw_bronze.custom_api_data": ["acme_edw_dev"],
        "edw_bronze.customers": ["acme_edw_dev"],
        "edw_bronze.customers_clustered": ["acme_edw_dev"],
        "edw_bronze.customers_clustered_with_row_filter": ["acme_edw_dev"],
        "edw_bronze.customers_partitioned": ["acme_edw_dev"],
        "edw_bronze.helper_enriched": ["acme_edw_dev"],
        "edw_bronze.helper_loaded": ["acme_edw_dev"],
        "edw_bronze.helper_snapshot_dim": ["acme_edw_dev"],
        "edw_bronze.helper_source_data": ["acme_edw_dev"],
        "edw_bronze.python_load_customers": ["acme_edw_dev"],
        "edw_bronze.site_alpha_customer": ["acme_edw_dev"],
        "edw_bronze.site_beta_customer": ["acme_edw_dev"],
        "edw_gold.partsupp_modelled_fct": ["acme_edw_dev"],
        "edw_silver.cdf_probe_out": ["acme_edw_dev"],
        "edw_silver.configured_union": ["acme_edw_dev"],
        "edw_silver.customer_dim": ["acme_edw_dev"],
        "edw_silver.dim_sfcc_cust": ["acme_edw_dev"],
        "edw_silver.nation_dim": ["acme_edw_dev"],
        "edw_silver.opaque_read_out": ["acme_edw_dev"],
        "edw_silver.param_snapshot_dim": ["acme_edw_dev"],
        "edw_silver.partsupp_dim": ["acme_edw_dev"],
        "edw_silver.site_alpha_customer_dim": ["acme_edw_dev"],
        "edw_silver.site_beta_customer_dim": ["acme_edw_dev"],
        "edw_silver.supplier_dim": ["acme_edw_dev"],
    }

    def __lhp_unique(__lhp_key):
        __lhp_cats = __lhp_short.get(__lhp_key)
        if not __lhp_cats or len(__lhp_cats) != 1:
            return None
        __lhp_cat = __lhp_cats[0]
        return (__lhp_cat + "." + __lhp_key) if __lhp_cat else __lhp_key

    __lhp_parts = [
        __lhp_p.replace("`", "").strip().lower() for __lhp_p in __lhp_ref.split(".")
    ]
    if len(__lhp_parts) == 3:
        __lhp_canon = ".".join(__lhp_parts)
        __lhp_match = (
            __lhp_canon
            if __lhp_canon in __lhp_produced
            else __lhp_unique(".".join(__lhp_parts[1:]))
        )
    elif len(__lhp_parts) == 2:
        __lhp_match = __lhp_unique(".".join(__lhp_parts))
    else:
        __lhp_match = None
    if __lhp_match is None:
        return __lhp_ref
    __lhp_orig = __lhp_ref.split(".")
    __lhp_last = __lhp_orig[-1]
    __lhp_leaf = "" + __lhp_last.replace("`", "").strip() + "_bob"
    __lhp_orig[-1] = "`" + __lhp_leaf + "`" if "`" in __lhp_last else __lhp_leaf
    return ".".join(__lhp_orig)


from pyspark.sql import DataFrame


def union_configured_tables(df: DataFrame, spark, parameters) -> DataFrame:
    """Union the input view with every table named in parameters["tables"]."""
    result = df
    for t in parameters["tables"]:
        result = result.unionByName(
            spark.read.table(__lhp_sandbox_table(t)), allowMissingColumns=True
        )
    return result


def fstring_scoped_read(df: DataFrame, spark, run_id) -> DataFrame:
    """f-string spark.sql: the in-scope FQN sits fully inside the literal
    segment, so sandbox mode rewrites its leaf to the producer namespace; the
    trailing ``{run_id}`` interpolation is preserved verbatim."""
    extra = spark.sql(
        f"SELECT * FROM acme_edw_dev.edw_bronze.helper_snapshot_dim_bob WHERE v = {run_id}"
    )
    return df.unionByName(extra, allowMissingColumns=True)


def dict_bound_read(df: DataFrame, spark) -> DataFrame:
    """Name-bound container read: the spark.read.table argument resolves through
    a dict, so it is statically known but not a plain literal — sandbox mode
    leaves it untouched and folds an LHP-VAL-066 warning."""
    sources = {"helper": "acme_edw_dev.edw_bronze.helper_snapshot_dim"}
    return df.unionByName(spark.read.table(sources["helper"]), allowMissingColumns=True)


def dynamic_query_read(df: DataFrame, spark, parameters) -> DataFrame:
    """Opaque spark.sql: the query text is supplied at runtime, so its table
    references cannot be verified or rewritten — sandbox mode folds an
    LHP-VAL-067 advisory and leaves the body unchanged."""
    query = parameters["dynamic_query"]
    return df.unionByName(spark.sql(query), allowMissingColumns=True)
