# Generated by LakehousePlumber
# Pipeline: 16_temp_table
# FlowGroup: staging_chain

from pyspark.sql import DataFrame
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "16_temp_table"
FLOWGROUP_ID = "staging_chain"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_raw_orders():
    """Load raw orders from bronze for staging"""
    df = spark.readStream.table("acme_edw_dev.edw_bronze.orders")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.table(
    temporary=True,
)
def staging_orders():
    """Materialize raw orders as an intermediate staging table"""
    df = spark.readStream.table("v_raw_orders")

    return df


@dp.temporary_view(comment="Aggregate staged orders into daily summary")
def v_orders_summary():
    """Aggregate staged orders into daily summary"""
    df = spark.sql("""SELECT
  DATE(order_date) AS order_day,
  COUNT(*) AS order_count,
  SUM(total_amount) AS total_revenue
FROM staging_orders
GROUP BY DATE(order_date)""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_gold.orders_daily_summary",
    comment="Daily order summary computed off the staging temp_table",
    table_properties={},
)
def orders_daily_summary():
    """Write to acme_edw_dev.edw_gold.orders_daily_summary from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_orders_summary")

    return df
