pipeline: perf_raw
flowgroup: training_ingestion
presets:
  - default_delta_properties
use_template: json_ingestion_template
template_parameters:
  table_name: training_raw
  landing_folder: training
  schema_file: lineitem_schema
