"""File-header and content-normalization utilities."""
from __future__ import annotations

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path


def build_lhp_source_header(source_path: str) -> str:
    """Build the standard LHP-SOURCE header prepended to copied files."""
    return (
        f"# LHP-SOURCE: {source_path}\n"
        "# Generated by LakehousePlumber - DO NOT EDIT\n"
        "# Changes will be overwritten on next generation\n"
        "\n"
    )


def normalize_content(content: str) -> str:
    """Normalize file content for comparison.

    Args:
        content: Raw content string

    Returns:
        Normalized content string
    """
    lines = content.splitlines()
    normalized_lines = [line.rstrip() for line in lines]

    normalized = "\n".join(normalized_lines)
    if normalized and not normalized.endswith("\n"):
        normalized += "\n"

    return normalized


def write_normalized(path: "Path", content: str) -> None:
    """Write ``content`` to ``path`` after normalization, as UTF-8.

    Centralizes the project-wide invariant that every LHP-generated file is
    written as UTF-8 with normalized line endings and trimmed trailing
    whitespace. Callers should prefer this over ``path.write_text(...)``
    so the encoding choice does not silently drift to ``locale.getencoding()``
    on Windows runners.
    """
    path.write_text(normalize_content(content), encoding="utf-8")
