"""Unit tests for :class:`MonitoringFinalizerService` (P0-4 / B10).

Targets the two arms that the monitoring e2e baselines never exercise:

1. The destructive ``cleanup_artifacts`` branch that ``shutil.rmtree``s a
   generated pipeline directory when monitoring is disabled, gated on a
   substring match against ``monitoring.py`` for the
   ``FLOWGROUP_ID = "monitoring"`` marker (``monitoring_service.py`` L278-295).
2. The four ``finalize_artifacts`` raise paths that validate the monitoring
   job config: ``LHP-CFG-008`` (missing ``job_config_path``), ``LHP-IO-001``
   (file absent), ``LHP-IO-002`` (YAML parse error), and ``LHP-CFG-008``
   (top-level non-mapping). (``monitoring_service.py`` L156-216.)

The safety test encodes a known latent product bug (the substring match is
naive and matches the marker even inside a comment/string literal) as a
``strict`` xfail — see ``MONITORING-RMTREE-DEFER``. The product fix is
deferred and owner-owned; this suite does NOT edit ``monitoring_service.py``.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from lhp.core.coordination.monitoring_pipeline_builder import MonitoringBuildResult
from lhp.core.coordination.monitoring_service import MonitoringFinalizerService
from lhp.core.registry.factories import OrchestrationDependencies
from lhp.errors import LHPError
from lhp.models import MonitoringConfig, ProjectConfig

# The exact marker the production cleanup branch substring-matches against.
FLOWGROUP_MARKER = 'FLOWGROUP_ID = "monitoring"'

# A real generated monitoring.py opens with this assignment as a top-level
# statement; that is the only legitimate occurrence of the marker.
REAL_MONITORING_PY = f'{FLOWGROUP_MARKER}\n\n# generated by lhp\n'


def _make_pipeline_dir(parent: Path, name: str, monitoring_py_content: str) -> Path:
    """Create ``parent/name/monitoring.py`` with the given content."""
    pipeline_dir = parent / name
    pipeline_dir.mkdir(parents=True)
    (pipeline_dir / "monitoring.py").write_text(monitoring_py_content, encoding="utf-8")
    return pipeline_dir


def _make_service(
    project_root: Path,
    monitoring: MonitoringConfig | None,
) -> MonitoringFinalizerService:
    """Build a service over a real (default) substitution factory.

    The default :class:`OrchestrationDependencies` wires the real
    :class:`EnhancedSubstitutionManager`, which tolerates a missing
    substitution file — so no on-disk substitutions YAML is required.
    """
    project_config = ProjectConfig(name="acme", monitoring=monitoring)
    return MonitoringFinalizerService(
        project_config=project_config,
        project_root=project_root,
        dependencies=OrchestrationDependencies(),
    )


def _build_result(pipeline_name: str = "acme_event_log_monitoring") -> MonitoringBuildResult:
    """A minimal, render-able :class:`MonitoringBuildResult`.

    ``finalize_artifacts`` renders ``union_event_logs.py.j2`` from this
    ``template_context`` *before* it reaches the job-config validation; the
    keys below are exactly what that template consumes (``sources``,
    ``target_fqn``, ``checkpoint_path``, ``max_concurrent_streams``).
    ``context=None`` keeps the synthetic DLT flowgroup absent (notebook-only).
    """
    return MonitoringBuildResult(
        context=None,
        template_context={
            "sources": [("p1", "cat.sch.p1_event_log")],
            "target_fqn": "cat.sch.all_pipelines_event_log",
            "checkpoint_path": "/Volumes/cat/sch/chk",
            "max_concurrent_streams": 4,
        },
        eligible_pipelines=["p1"],
        pipeline_name=pipeline_name,
    )


# ---------------------------------------------------------------------------
# 1. cleanup-on-disable happy path
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_cleanup_on_disable_removes_marked_pipeline_dir(tmp_path):
    """When monitoring is disabled, the generated monitoring pipeline dir
    (whose ``monitoring.py`` legitimately carries the marker) IS removed."""
    project_root = tmp_path / "project"
    project_root.mkdir()
    output_dir = project_root / "generated"

    marked_dir = _make_pipeline_dir(output_dir, "monitoring_pipeline", REAL_MONITORING_PY)
    # An unrelated pipeline dir with no marker must survive.
    unrelated_dir = _make_pipeline_dir(
        output_dir, "ingest_pipeline", "FLOWGROUP_ID = \"ingest\"\n"
    )

    # Monitoring disabled -> service.last_build_result stays None -> rmtree arm.
    service = _make_service(project_root, monitoring=None)
    assert service.last_build_result is None

    service.cleanup_artifacts(env="dev", output_dir=output_dir)

    assert not marked_dir.exists(), "marked monitoring pipeline dir should be removed"
    assert unrelated_dir.exists(), "unrelated pipeline dir must be preserved"


# ---------------------------------------------------------------------------
# 2. finalize_artifacts — the four raise paths
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_finalize_raises_cfg008_when_job_config_path_missing(tmp_path):
    """LHP-CFG-008: monitoring enabled but ``job_config_path`` is unset."""
    project_root = tmp_path / "project"
    project_root.mkdir()
    output_dir = project_root / "generated"

    service = _make_service(
        project_root,
        monitoring=MonitoringConfig(enabled=True, job_config_path=None),
    )
    service._last_build_result = _build_result()

    with pytest.raises(LHPError, match="LHP-CFG-008"):
        service.finalize_artifacts(env="dev", output_dir=output_dir)


@pytest.mark.unit
def test_finalize_raises_io001_when_job_config_file_absent(tmp_path):
    """LHP-IO-001: ``job_config_path`` points at a non-existent file."""
    project_root = tmp_path / "project"
    project_root.mkdir()
    output_dir = project_root / "generated"

    service = _make_service(
        project_root,
        monitoring=MonitoringConfig(
            enabled=True, job_config_path="config/missing_job.yaml"
        ),
    )
    service._last_build_result = _build_result()

    with pytest.raises(LHPError, match="LHP-IO-001"):
        service.finalize_artifacts(env="dev", output_dir=output_dir)


@pytest.mark.unit
def test_finalize_raises_io002_on_malformed_job_config_yaml(tmp_path):
    """LHP-IO-002: ``job_config_path`` file exists but is invalid YAML."""
    project_root = tmp_path / "project"
    project_root.mkdir()
    output_dir = project_root / "generated"

    config_dir = project_root / "config"
    config_dir.mkdir()
    # Unbalanced bracket -> yaml.YAMLError on parse.
    (config_dir / "job.yaml").write_text("key: [unclosed\n", encoding="utf-8")

    service = _make_service(
        project_root,
        monitoring=MonitoringConfig(enabled=True, job_config_path="config/job.yaml"),
    )
    service._last_build_result = _build_result()

    with pytest.raises(LHPError, match="LHP-IO-002"):
        service.finalize_artifacts(env="dev", output_dir=output_dir)


@pytest.mark.unit
def test_finalize_raises_cfg008_when_job_config_not_a_mapping(tmp_path):
    """LHP-CFG-008: ``job_config_path`` file parses to a non-mapping (list)."""
    project_root = tmp_path / "project"
    project_root.mkdir()
    output_dir = project_root / "generated"

    config_dir = project_root / "config"
    config_dir.mkdir()
    # Valid YAML, but a top-level sequence rather than a mapping.
    (config_dir / "job.yaml").write_text("- not\n- a\n- mapping\n", encoding="utf-8")

    service = _make_service(
        project_root,
        monitoring=MonitoringConfig(enabled=True, job_config_path="config/job.yaml"),
    )
    service._last_build_result = _build_result()

    with pytest.raises(LHPError, match="LHP-CFG-008"):
        service.finalize_artifacts(env="dev", output_dir=output_dir)


# ---------------------------------------------------------------------------
# 3. Safety test — known latent bug, encoded as strict xfail (DO NOT fix code)
# ---------------------------------------------------------------------------


@pytest.mark.unit
def test_cleanup_does_not_delete_dir_with_marker_only_in_comment(tmp_path):
    """A user pipeline whose ``monitoring.py`` mentions the marker only inside
    a comment/string (a false match) must NOT be ``rmtree``d.

    The production cleanup gate is a naive ``in`` substring test, so the
    false-match dir is deleted and this assertion fails -> reported as xfail.
    If the substring match is ever tightened (bug fixed), this XPASSes and
    ``strict=True`` flips it to a failure, alerting the owner.
    """
    project_root = tmp_path / "project"
    project_root.mkdir()
    output_dir = project_root / "generated"

    # The marker appears ONLY inside a comment and a string literal here — this
    # is a user pipeline that happens to reference the marker text, NOT a
    # generated monitoring pipeline.
    false_match_py = (
        "# This module is unrelated to monitoring.\n"
        f"# Note: the generator stamps {FLOWGROUP_MARKER} into monitoring files.\n"
        f'DOC = "see also: {FLOWGROUP_MARKER}"\n'
        'FLOWGROUP_ID = "user_ingest"\n'
    )
    false_match_dir = _make_pipeline_dir(output_dir, "user_pipeline", false_match_py)

    service = _make_service(project_root, monitoring=None)
    assert service.last_build_result is None

    service.cleanup_artifacts(env="dev", output_dir=output_dir)

    # Expected-correct behavior: the false-match dir survives. The buggy
    # production substring match deletes it, so this assertion fails (xfail).
    assert false_match_dir.exists(), (
        "user pipeline dir whose monitoring.py only mentions the marker in a "
        "comment/string must NOT be deleted"
    )
