# Generated by LakehousePlumber
# Pipeline: acmi_edw_bronze
# FlowGroup: region_bronze

from pyspark import pipelines as dp
from pyspark.sql import functions as F

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_bronze"
FLOWGROUP_ID = "region_bronze"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_region_raw():
    """Load region table from raw schema"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.region_raw")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view(comment="SQL transform: region_bronze_incremental_cleanse")
def v_region_bronze_cleaned():
    """SQL transform: region_bronze_incremental_cleanse"""
    df = spark.sql("""SELECT
  xxhash64(r_regionkey,r_name,r_comment) as region_key,
  r_regionkey as region_id,
  r_name as name,
  r_comment as comment,
  * EXCEPT(r_regionkey, r_name, r_comment,_rescued_data)
FROM stream(v_region_raw)""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.region",
    comment="Streaming table: region",
    table_properties={"delta.enableRowTracking": "true"},
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.region",
    name="f_region_bronze_incremental",
    comment="Append flow to acme_edw_dev.edw_bronze.region",
)
def f_region_bronze_incremental():
    """Append flow to acme_edw_dev.edw_bronze.region"""
    # Streaming flow
    df = spark.readStream.table("v_region_bronze_cleaned")

    return df
