# Generated by LakehousePlumber
# Pipeline: 12_test_actions
# FlowGroup: ta_all_lookups_found

from pyspark.sql.functions import *
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "12_test_actions"
FLOWGROUP_ID = "ta_all_lookups_found"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all({"all_lookups_found": "lookup_date_key IS NOT NULL"})
@dp.table(
    name="tmp_test_ta_orders_date_lookup",
    comment="Ensure all order dates resolve to a date dimension key",
    temporary=True,
)
def tmp_test_ta_orders_date_lookup():
    """Ensure all order dates resolve to a date dimension key"""
    return spark.sql("""
        SELECT
                      s.*,
                      l.date_key as lookup_date_key
                    FROM acme_edw_dev.edw_silver.fact_orders s
                    LEFT JOIN acme_edw_dev.edw_gold.dim_date l ON s.order_date = l.order_date
    """)
