# Generated by LakehousePlumber
# Pipeline: 12_test_actions
# FlowGroup: ta_custom_expectations

from pyspark.sql.functions import *
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "12_test_actions"
FLOWGROUP_ID = "ta_custom_expectations"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all(
    {
        "positive_amount": "total_price > 0",
        "reasonable_discount": "discount_percent <= 50",
    }
)
@dp.table(
    name="tmp_test_ta_orders_business_rules",
    comment="Validate business rules on fact_orders",
    temporary=True,
)
def tmp_test_ta_orders_business_rules():
    """Validate business rules on fact_orders"""
    return spark.sql("""
        SELECT * FROM acme_edw_dev.edw_silver.fact_orders
    """)
