# Generated by LakehousePlumber
# Pipeline: 12_test_actions
# FlowGroup: ta_custom_sql

from pyspark.sql.functions import *
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "12_test_actions"
FLOWGROUP_ID = "ta_custom_sql"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all({"revenue_matches": "pct_difference < 0.5"})
@dp.table(
    name="tmp_test_ta_revenue_reconciliation",
    comment="Reconcile gold vs silver monthly revenue within 0.5%",
    temporary=True,
)
def tmp_test_ta_revenue_reconciliation():
    """Reconcile gold vs silver monthly revenue within 0.5%"""
    return spark.sql("""
        SELECT month, gold_revenue, silver_revenue,
               (ABS(gold_revenue - silver_revenue) / silver_revenue) * 100 AS pct_difference
        FROM acme_edw_dev.edw_gold.revenue_comparison
    """)
