# Generated by LakehousePlumber
# Pipeline: 12_test_actions
# FlowGroup: ta_referential_integrity

from pyspark.sql.functions import *
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "12_test_actions"
FLOWGROUP_ID = "ta_referential_integrity"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all({"referential_integrity": "ref_customer_id IS NOT NULL"})
@dp.table(
    name="tmp_test_ta_orders_customer_fk",
    comment="Ensure orders reference valid customers",
    temporary=True,
)
def tmp_test_ta_orders_customer_fk():
    """Ensure orders reference valid customers"""
    return spark.sql("""
        SELECT
                      s.*,
                      r.customer_id as ref_customer_id
                    FROM acme_edw_dev.edw_silver.fact_orders s
                    LEFT JOIN acme_edw_dev.edw_silver.dim_customer r ON s.customer_id = r.customer_id
    """)
