# Generated by LakehousePlumber
# Pipeline: 12_test_actions
# FlowGroup: ta_row_count

from pyspark.sql.functions import *
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "12_test_actions"
FLOWGROUP_ID = "ta_row_count"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all({"row_count_match": "abs(source_count - target_count) <= 0"})
@dp.table(
    name="tmp_test_ta_row_count_raw_to_bronze",
    comment="Ensure no data loss from raw to bronze",
    temporary=True,
)
def tmp_test_ta_row_count_raw_to_bronze():
    """Ensure no data loss from raw to bronze"""
    return spark.sql("""
        SELECT * FROM
                      (SELECT COUNT(*) AS source_count FROM acme_edw_dev.edw_raw.customers),
                      (SELECT COUNT(*) AS target_count FROM acme_edw_dev.edw_bronze.customers)
    """)
