# Generated by LakehousePlumber
# Pipeline: 12_test_actions
# FlowGroup: ta_schema_match

from pyspark.sql.functions import *
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "12_test_actions"
FLOWGROUP_ID = "ta_schema_match"


# ============================================================================
# DATA QUALITY TESTS
# ============================================================================


@dp.expect_all({"schemas_match": "false"})
@dp.table(
    name="tmp_test_ta_orders_schema_match",
    comment="Ensure orders schema matches expected reference",
    temporary=True,
)
def tmp_test_ta_orders_schema_match():
    """Ensure orders schema matches expected reference"""
    return spark.sql("""
        WITH source_schema AS (
                      SELECT column_name, data_type, ordinal_position
                      FROM acme_edw_dev.information_schema.columns
                      WHERE table_catalog = 'acme_edw_dev'
                        AND table_schema = 'edw_silver'
                        AND table_name = 'fact_orders'
                    ),
                    reference_schema AS (
                      SELECT column_name, data_type, ordinal_position
                      FROM acme_edw_dev.information_schema.columns
                      WHERE table_catalog = 'acme_edw_dev'
                        AND table_schema = 'edw_gold'
                        AND table_name = 'fact_orders_expected'
                    ),
                    schema_diff AS (
                      SELECT
                        COALESCE(s.column_name, r.column_name) as column_name,
                        s.data_type as source_type,
                        r.data_type as reference_type,
                        CASE
                          WHEN s.column_name IS NULL THEN 'missing_in_source'
                          WHEN r.column_name IS NULL THEN 'extra_in_source'
                          WHEN s.data_type != r.data_type THEN 'type_mismatch'
                          ELSE 'match'
                        END as status
                      FROM source_schema s
                      FULL OUTER JOIN reference_schema r ON s.column_name = r.column_name
                    )
                    SELECT * FROM schema_diff WHERE status != 'match'
    """)
