# Generated by LakehousePlumber
# Pipeline: namespace_validation
# FlowGroup: namespace_streaming

from pyspark import pipelines as dp
from pyspark.sql import functions as F

# Pipeline Configuration
PIPELINE_ID = "namespace_validation"
FLOWGROUP_ID = "namespace_streaming"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_ns_customer():
    """Load customer from bronze (namespace format)"""
    df = spark.readStream.table("acme_edw_dev.edw_bronze.customer")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_silver.namespace_validation_st",
    comment="Streaming table: namespace_validation_st",
    table_properties={"delta.enableRowTracking": "true"},
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_silver.namespace_validation_st",
    name="f_ns_streaming",
    comment="Append flow to acme_edw_dev.edw_silver.namespace_validation_st",
)
def f_ns_streaming():
    """Append flow to acme_edw_dev.edw_silver.namespace_validation_st"""
    # Streaming flow
    df = spark.readStream.table("v_ns_customer")

    return df
