# Generated by LakehousePlumber
# Pipeline: namespace_validation
# FlowGroup: namespace_mv

from pyspark import pipelines as dp
from pyspark.sql import DataFrame

# Pipeline Configuration
PIPELINE_ID = "namespace_validation"
FLOWGROUP_ID = "namespace_mv"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_ns_summary():
    """SQL source: ns_summary_sql"""
    df = spark.sql("""SELECT
  customer_id,
  name,
  market_segment
FROM acme_edw_dev.edw_silver.customer_dim
""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_gold.namespace_validation_mv",
    comment="Materialized view: namespace_validation_mv",
    table_properties={},
)
def namespace_validation_mv():
    """Write to acme_edw_dev.edw_gold.namespace_validation_mv from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_ns_summary")

    return df
