# Generated by LakehousePlumber
# Pipeline: gold_load
# FlowGroup: order_summary_mv

from pyspark import pipelines as dp
from pyspark.sql import DataFrame

# Pipeline Configuration
PIPELINE_ID = "gold_load"
FLOWGROUP_ID = "order_summary_mv"


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_gold.order_summary_mv",
    comment="Gold materialized view: order summary aggregations",
    table_properties={},
)
def order_summary_mv():
    """Write order summary materialized view to gold schema"""
    # Materialized views use batch processing
    df = spark.sql("""SELECT
  o.order_year,
  o.order_month,
  COUNT(DISTINCT o.order_key) AS total_orders,
  COUNT(DISTINCT o.customer_key) AS unique_customers,
  SUM(o.total_price) AS total_revenue,
  AVG(o.total_price) AS avg_order_value
FROM acme_edw_dev.edw_silver.orders o
GROUP BY o.order_year, o.order_month
ORDER BY o.order_year, o.order_month""")

    return df
