# Generated by LakehousePlumber
# Pipeline: acmi_edw_silver
# FlowGroup: customer_silver_dim

from pyspark.sql import functions as F
import dlt

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_silver"
FLOWGROUP_ID = "customer_silver_dim"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dlt.view()
def v_customer_bronze():
    """Load customer table from silver schema"""
    df = spark.readStream.table("acme_edw_dev.edw_bronze.customer")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table for CDC
dlt.create_streaming_table(
    name="acme_edw_dev.edw_silver.customer_dim",
    comment="Streaming table: customer_dim",
    table_properties={"delta.enableRowTracking": "true"},
)

# CDC mode using auto_cdc
dlt.create_auto_cdc_flow(
    target="acme_edw_dev.edw_silver.customer_dim",
    source="v_customer_bronze",
    keys=["customer_id"],
    sequence_by="last_modified_dt",
    stored_as_scd_type=2,
    track_history_except_column_list=[
        "_source_file_path",
        "_processing_timestamp",
        "customer_key",
        "last_modified_dt",
    ],
    ignore_null_updates=True,
)
