"""Final code assembly: imports, pre-pipeline statements, headers, pipeline-id.

:stability: internal
"""

import logging
from typing import List, Set

from lhp.models import FlowGroup
from .imports import ImportManager, extract_future_imports


class CodeAssembler:
    """Assemble the final pipeline Python module string.

    Hoists every ``from __future__ import ...`` statement to the top of the
    file (PEP 236), sort-categorizes the remaining imports via
    :class:`ImportManager` (PEP 8 grouping: stdlib -> third-party -> pyspark
    -> dlt -> custom), emits a sorted pre-pipeline statements block, and
    appends the ``PIPELINE_ID`` / ``FLOWGROUP_ID`` header before the
    generated body.

    :stability: internal
    """

    def __init__(self) -> None:
        self.logger = logging.getLogger(__name__)

    def assemble(
        self,
        flowgroup: FlowGroup,
        all_imports: Set[str],
        pre_pipeline_statements: Set[str],
        complete_code: str,
    ) -> str:
        """Assemble final Python code with headers and imports.

        Enforces PEP 236 by hoisting every ``from __future__ import ...``
        statement collected from the imports set and the main generated body
        to the top of the assembled module — a single chokepoint so individual
        generators do not need to know about future imports.

        The pre-pipeline statements set (e.g. ``cloudpickle.register_pickle_by_value``
        for custom data sources/sinks) is emitted as a sorted block immediately
        after the imports block and before ``PIPELINE_ID``.
        """
        self.logger.debug(
            f"Assembling final code for flowgroup '{flowgroup.flowgroup}' with "
            f"{len(all_imports)} imports, "
            f"{len(pre_pipeline_statements)} pre-pipeline statements"
        )

        # (a) Pull __future__ statements out of the collected imports set.
        future_imports: List[str] = []
        non_future: Set[str] = set()
        for imp in all_imports:
            if imp.lstrip().startswith("from __future__"):
                future_imports.append(imp.strip())
            else:
                non_future.add(imp)

        # (b) Pull __future__ out of the main generated code body (e.g.
        # snapshot-CDC source_function_code inlined into the streaming_table
        # template).
        fl, complete_code = extract_future_imports(complete_code)
        future_imports.extend(fl)

        # Dedupe in declaration order.
        seen: Set[str] = set()
        ordered_futures = [f for f in future_imports if not (f in seen or seen.add(f))]

        # Category-aware ordering for the rest (replaces sorted(all_imports)).
        # Reuses ImportManager._sort_imports via a transient instance so we get
        # PEP 8 style grouping (stdlib -> third-party -> pyspark -> dlt -> custom)
        # rather than ASCII-sorted output.
        mgr = ImportManager()
        for imp in non_future:
            mgr.add_import(imp)
        sorted_non_future = mgr.get_consolidated_imports()

        import_block_lines: List[str] = []
        if ordered_futures:
            import_block_lines.extend(ordered_futures)
            import_block_lines.append("")
        import_block_lines.extend(sorted_non_future)
        imports_section = "\n".join(import_block_lines)

        # Pre-pipeline statements block (sorted for deterministic output).
        pre_pipeline_block = ""
        if pre_pipeline_statements:
            pre_pipeline_block = (
                "\n" + "\n".join(sorted(pre_pipeline_statements)) + "\n"
            )

        pipeline_config = f"""
# Pipeline Configuration
PIPELINE_ID = "{flowgroup.pipeline}"
FLOWGROUP_ID = "{flowgroup.flowgroup}"
"""

        header = f"""# Generated by LakehousePlumber
# Pipeline: {flowgroup.pipeline}
# FlowGroup: {flowgroup.flowgroup}

{imports_section}
{pre_pipeline_block}{pipeline_config}"""

        return header + "\n\n" + complete_code
