# Generated by LakehousePlumber
# Pipeline: bronze_orders
# FlowGroup: orders_ingest

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "bronze_orders"
FLOWGROUP_ID = "orders_ingest"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_orders_raw():
    """Load data from csv files at /Volumes/dev_catalog/landing/files/orders/*.csv"""
    df = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "csv")
        .load("/Volumes/dev_catalog/landing/files/orders/*.csv")
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="dev_catalog.bronze.alice_orders", comment="Streaming table: alice_orders"
)


# Define append flow(s)
@dp.append_flow(
    target="dev_catalog.bronze.alice_orders",
    name="f_orders_bronze",
    comment="Append flow to dev_catalog.bronze.alice_orders",
)
def f_orders_bronze():
    """Append flow to dev_catalog.bronze.alice_orders"""
    # Streaming flow
    df = spark.readStream.table("v_orders_raw")

    return df
