# Generated by LakehousePlumber
# Pipeline: bronze_orders
# FlowGroup: orders_enriched

from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "bronze_orders"
FLOWGROUP_ID = "orders_enriched"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_orders():
    """Delta source: dev_catalog.bronze.alice_orders"""
    df = spark.readStream.table("dev_catalog.bronze.alice_orders")

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view(comment="SQL transform: enrich_orders")
def v_orders_enriched():
    """SQL transform: enrich_orders"""
    df = spark.sql("""SELECT
  o.*,
  c.customer_name,
  c.region
FROM stream(v_orders) o
LEFT JOIN dev_catalog.raw.customers c
  ON o.customer_id = c.customer_id""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="dev_catalog.bronze.alice_orders_enriched",
    comment="Streaming table: alice_orders_enriched",
)


# Define append flow(s)
@dp.append_flow(
    target="dev_catalog.bronze.alice_orders_enriched",
    name="f_orders_enriched",
    comment="Append flow to dev_catalog.bronze.alice_orders_enriched",
)
def f_orders_enriched():
    """Append flow to dev_catalog.bronze.alice_orders_enriched"""
    # Streaming flow
    df = spark.readStream.table("v_orders_enriched")

    return df
