pipeline: perf_raw
flowgroup: producer_ingestion
presets:
  - default_delta_properties
use_template: parquet_ingestion_template
template_parameters:
  table_name: producer_raw
  landing_folder: producer
  schema_file: nation_schema
