"""Monitoring finalizer service.

Extracted from :class:`ActionOrchestrator` to satisfy
:class:`BaseMonitoringFinalizerService`.

:stability: provisional
"""

import logging
from pathlib import Path
from typing import Optional, Sequence

from lhp.core._interfaces import BaseMonitoringFinalizerService
from lhp.core.registry import OrchestrationDependencies
from lhp.errors import ErrorFactory, codes
from lhp.models import FlowGroup, ProjectConfig
from lhp.utils.file_header import write_normalized

from .monitoring_pipeline_builder import (
    MonitoringBuildResult,
    MonitoringPipelineBuilder,
)


class MonitoringFinalizerService(BaseMonitoringFinalizerService):
    """Build and finalize monitoring artifacts.

    Owns the :class:`MonitoringBuildResult` state across the
    build/finalize/cleanup trio.

    :stability: provisional
    """

    _MONITORING_JOB_HEADER = "# Generated by LakehousePlumber - Monitoring Job"
    _FLOWGROUP_ID_MARKER = 'FLOWGROUP_ID = "monitoring"'

    def __init__(
        self,
        project_config: Optional[ProjectConfig],
        project_root: Path,
        dependencies: OrchestrationDependencies,
        pipeline_config_path: Optional[str] = None,
        logger: Optional[logging.Logger] = None,
    ) -> None:
        self.project_config = project_config
        self.project_root = project_root
        self.dependencies = dependencies
        self.pipeline_config_path = pipeline_config_path
        self.logger = logger if logger is not None else logging.getLogger(__name__)

        self._last_build_result: Optional[MonitoringBuildResult] = None

    @property
    def last_build_result(self) -> Optional[MonitoringBuildResult]:
        """Most recent :class:`MonitoringBuildResult` (or ``None``)."""
        return self._last_build_result

    def build_flowgroup(
        self, discovered_flowgroups: Sequence[FlowGroup]
    ) -> Optional[FlowGroup]:
        """Build the synthetic monitoring flowgroup, or ``None``.

        Lifted from ``ActionOrchestrator._build_monitoring``. ABC narrows
        the return to ``Optional[FlowGroup]``; remaining
        :class:`MonitoringBuildResult` fields stay on
        ``self._last_build_result``.
        """
        if not self.project_config or not self.project_config.monitoring:
            self._last_build_result = None
            return None

        from lhp.core.loaders.pipeline_config_loader import PipelineConfigLoader

        # Resolve monitoring pipeline name for alias support in pipeline config
        monitoring_pipeline_name = None
        if self.project_config and self.project_config.monitoring:
            m = self.project_config.monitoring
            if m.enabled:
                monitoring_pipeline_name = (
                    m.pipeline_name
                    or f"{self.project_config.name}_event_log_monitoring"
                )

        pipeline_config_loader = PipelineConfigLoader(
            self.project_root,
            self.pipeline_config_path,
            monitoring_pipeline_name=monitoring_pipeline_name,
        )

        builder = MonitoringPipelineBuilder(
            project_config=self.project_config,
            pipeline_config_loader=pipeline_config_loader,
            project_root=self.project_root,
        )

        # Extract unique pipeline names from discovered flowgroups
        pipeline_names = list(
            dict.fromkeys(fg.pipeline for fg in discovered_flowgroups)
        )

        result = builder.build(pipeline_names)
        self._last_build_result = result
        return result.flowgroup if result is not None else None

    def finalize_artifacts(self, env: str, output_dir: Path) -> None:
        """Reconcile monitoring artifacts: clean stale, write current.

        Lifted verbatim from
        ``ActionOrchestrator.finalize_monitoring_artifacts``. Called AFTER
        the pipeline generation loop. Handles add/remove/rename
        transitions and notebook-only vs full job updates.
        """
        self.cleanup_artifacts(env, output_dir)

        if not self._last_build_result:
            return

        substitution_file = self.project_root / "substitutions" / f"{env}.yaml"
        substitution_mgr = self.dependencies.create_substitution_manager(
            substitution_file, env
        )

        resolved_context = substitution_mgr.substitute_yaml(
            self._last_build_result.template_context
        )

        from lhp.core.codegen.template_renderer import TemplateRenderer

        renderer = TemplateRenderer.from_package()
        notebook_content = renderer.render_template(
            "monitoring/union_event_logs.py.j2", resolved_context
        )

        monitoring_pipeline_name = self._last_build_result.pipeline_name

        monitoring_dir = self.project_root / "monitoring" / env
        monitoring_dir.mkdir(parents=True, exist_ok=True)
        notebook_path = monitoring_dir / "union_event_logs.py"
        write_normalized(notebook_path, notebook_content)
        self.logger.info(f"Generated monitoring notebook: {notebook_path}")

        import yaml

        from ..jobs.job_generator import JobGenerator

        raw_job_config_rel_path = self.project_config.monitoring.job_config_path
        # Substitute tokens (e.g. ${env}) in the path; tokenized paths only
        # resolve once the environment is known.
        job_config_rel_path = (
            substitution_mgr.substitute_yaml(raw_job_config_rel_path)
            if raw_job_config_rel_path
            else raw_job_config_rel_path
        )
        # Defensive: orchestration also runs through code paths that bypass
        # ProjectConfigLoader validation (tests), and tokenized paths only
        # resolve at this stage.
        if not job_config_rel_path:
            raise ErrorFactory.config_error(
                codes.CFG_008,
                title="Monitoring job_config_path is required",
                details=(
                    "monitoring.job_config_path must be set when monitoring is enabled."
                ),
                suggestions=[
                    "Add job_config_path to your monitoring config in lhp.yaml",
                    "Example: job_config_path: config/monitoring_job_config.yaml",
                ],
            )

        job_config_file = self.project_root / job_config_rel_path
        if not job_config_file.is_file():
            raise ErrorFactory.io_error(
                codes.IO_001,
                title="Monitoring job_config file not found",
                details=(
                    f"monitoring.job_config_path points to '{job_config_rel_path}', "
                    f"but no file exists at {job_config_file}."
                ),
                suggestions=[
                    "Create the file at the configured path",
                    "Or update monitoring.job_config_path to a valid location",
                ],
                context={
                    "File Path": str(job_config_rel_path),
                    "Project Root": str(self.project_root),
                },
            )

        try:
            with open(job_config_file, "r", encoding="utf-8") as f:
                raw_job_config = yaml.safe_load(f) or {}
        except yaml.YAMLError as e:
            raise ErrorFactory.io_error(
                codes.IO_002,
                title="Invalid monitoring job_config YAML",
                details=f"Failed to parse {job_config_file}: {e}",
                suggestions=["Fix the YAML syntax in the monitoring job config"],
                context={"File Path": str(job_config_file)},
            ) from e

        if not isinstance(raw_job_config, dict):
            raise ErrorFactory.config_error(
                codes.CFG_008,
                title="Invalid monitoring job_config structure",
                details=(
                    f"{job_config_file} must contain a YAML mapping at the top level, "
                    f"got {type(raw_job_config).__name__}."
                ),
                suggestions=[
                    "Use a flat single-document mapping (no 'project_defaults' wrapper, "
                    "no 'job_name' key)",
                ],
            )

        substituted_job_config = substitution_mgr.substitute_yaml(raw_job_config)
        resolved_job_config = JobGenerator.resolve_monitoring_job_config(
            substituted_job_config
        )

        job_name = f"{monitoring_pipeline_name}_job"
        job_gen = JobGenerator(project_root=self.project_root)
        notebook_workspace_path = (
            "${workspace.file_path}/monitoring/${bundle.target}/union_event_logs"
        )
        has_pipeline = self._last_build_result.flowgroup is not None
        job_resource_content = job_gen.generate_monitoring_job(
            pipeline_name=monitoring_pipeline_name,
            notebook_path=notebook_workspace_path,
            job_name=job_name,
            job_config=resolved_job_config,
            has_pipeline=has_pipeline,
        )
        resources_dir = self.project_root / "resources"
        resources_dir.mkdir(parents=True, exist_ok=True)
        job_resource_path = resources_dir / f"{monitoring_pipeline_name}.job.yml"
        write_normalized(job_resource_path, job_resource_content)
        self.logger.info(f"Generated monitoring job resource: {job_resource_path}")

    def cleanup_artifacts(self, env: str, output_dir: Path) -> None:
        """Remove existing monitoring artifacts before writing new ones.

        Invoked from :meth:`finalize_artifacts` as the first step of the
        reconcile pass.
        """
        monitoring_dir = self.project_root / "monitoring" / env
        if monitoring_dir.exists():
            for f in monitoring_dir.iterdir():
                if f.is_file():
                    f.unlink()
                    self.logger.info(f"Removed monitoring artifact: {f}")
            if not any(monitoring_dir.iterdir()):
                monitoring_dir.rmdir()
                self.logger.debug(f"Removed empty directory: {monitoring_dir}")
            monitoring_parent = monitoring_dir.parent
            if monitoring_parent.exists() and not any(monitoring_parent.iterdir()):
                monitoring_parent.rmdir()
                self.logger.debug(f"Removed empty directory: {monitoring_parent}")

        resources_dir = self.project_root / "resources"
        if resources_dir.exists():
            for f in resources_dir.iterdir():
                if f.is_file() and f.suffix == ".yml" and f.name.endswith(".job.yml"):
                    try:
                        first_line = f.read_text().split("\n", 1)[0]
                        if first_line.startswith(self._MONITORING_JOB_HEADER):
                            f.unlink()
                            self.logger.info(f"Removed monitoring job: {f}")
                    except OSError as exc:
                        self.logger.debug(f"failed to read {f}: {exc}")

        # Only when monitoring is removed/disabled — when monitoring IS
        # configured, the pipeline generation loop manages the generated/
        # directory. Synthetic monitoring flowgroups aren't tracked in state,
        # so orphan detection misses them; identify by FLOWGROUP_ID marker.
        if not self._last_build_result and output_dir and output_dir.exists():
            import shutil

            for pipeline_dir in output_dir.iterdir():
                if not pipeline_dir.is_dir():
                    continue
                monitoring_py = pipeline_dir / "monitoring.py"
                if not monitoring_py.exists():
                    continue
                try:
                    content = monitoring_py.read_text(encoding="utf-8")
                    if self._FLOWGROUP_ID_MARKER in content.splitlines():
                        shutil.rmtree(pipeline_dir)
                        self.logger.info(
                            f"Removed monitoring pipeline directory: {pipeline_dir}"
                        )
                except OSError as exc:
                    self.logger.debug(f"failed to read {monitoring_py}: {exc}")
