# Generated by LakehousePlumber
# Pipeline: acmi_edw_bronze
# FlowGroup: lineitem_bronze_middle_east

from pyspark import pipelines as dp
from pyspark.sql import functions as F

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_bronze"
FLOWGROUP_ID = "lineitem_bronze_middle_east"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_lineitem_middle_east_raw():
    """Load lineitem table from raw schema"""
    df = spark.readStream.table("acme_edw_tst.edw_raw.lineitem_middle_east_raw")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view(comment="SQL transform: lineitem_bronze_cleanse")
def v_lineitem_middle_east_bronze_cleaned():
    """SQL transform: lineitem_bronze_cleanse"""
    df = spark.sql(
        """SELECT
  l_orderkey as order_id,
  l_partkey as part_id,
  l_suppkey as supplier_id,
  l_linenumber as line_number,
  l_quantity as quantity,
  l_extendedprice as extended_price,
  l_discount as discount,
  l_tax as tax,
  l_returnflag as return_flag,
  l_linestatus as line_status,
  l_shipdate as ship_date,
  l_commitdate as commit_date,
  l_receiptdate as receipt_date,
  l_shipinstruct as ship_instruct,
  l_shipmode as ship_mode,
  l_comment as comment,
  cast(last_modified_dt as TIMESTAMP) as last_modified_dt,
  * EXCEPT(l_orderkey, l_partkey, l_suppkey, l_linenumber, l_quantity, l_extendedprice, l_discount, l_tax, l_returnflag, l_linestatus, l_shipdate, l_commitdate, l_receiptdate, l_shipinstruct, l_shipmode, l_comment,last_modified_dt,_rescued_data)
FROM stream(v_lineitem_middle_east_raw)"""
    )

    return df


@dp.temporary_view()
# These expectations will fail the pipeline if violated
@dp.expect_all_or_fail(
    {
        "valid_order_id": "order_id IS NOT NULL AND order_id > 0",
        "valid_part_id": "part_id IS NOT NULL AND part_id > 0",
        "valid_supplier_id": "supplier_id IS NOT NULL AND supplier_id > 0",
        "valid_linenumber": "line_number IS NOT NULL AND line_number > 0",
        "valid_quantity": "quantity IS NOT NULL AND quantity > 0",
        "valid_extendedprice": "extended_price IS NOT NULL AND extended_price > 0",
    }
)
# These expectations will log warnings but not drop rows
@dp.expect_all(
    {
        "valid_discount": "discount IS NOT NULL AND discount > 0",
        "valid_tax": "tax IS NOT NULL AND tax > 0",
        "valid_return_flag": "return_flag IS NULL OR return_flag IN ('R', 'N')",
        "valid_line_status": "line_status IS NULL OR line_status IN ('F', 'O')",
        "valid_ship_date": "(ship_date IS NOT NULL AND ship_date >= '1900-01-01') or ship_date is null",
        "valid_commit_date": "commit_date IS NOT NULL AND commit_date >= '1900-01-01'",
        "valid_receipt_date": "(receipt_date IS NOT NULL AND receipt_date >= '1900-01-01') or receipt_date is null",
        "valid_ship_mode": "ship_mode IS NOT NULL AND ship_mode IN ('RAIL','REG AIR','TRUCK','MAIL','SHIP','FOB')",
    }
)
def v_lineitem_middle_east_bronze_DQE():
    """Apply data quality checks to lineitem"""
    df = spark.readStream.table("v_lineitem_middle_east_bronze_cleaned")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_tst.edw_bronze.lineitem",
    name="f_lineitem_middle_east_bronze",
    comment="Append flow to acme_edw_tst.edw_bronze.lineitem",
)
def f_lineitem_middle_east_bronze():
    """Append flow to acme_edw_tst.edw_bronze.lineitem"""
    # Streaming flow
    df = spark.readStream.table("v_lineitem_middle_east_bronze_DQE")

    return df
