# Generated by LakehousePlumber
# Pipeline: acmi_edw_raw
# FlowGroup: orders_ingestion_middle_east

from pyspark import pipelines as dp
from pyspark.sql import functions as F

# Pipeline Configuration
PIPELINE_ID = "acmi_edw_raw"
FLOWGROUP_ID = "orders_ingestion_middle_east"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.view()
def v_orders_middle_east_raw_cloudfiles():
    """Load orders_middle_east_raw Parquet files from landing volume"""
    df = (
        spark.readStream.format("cloudFiles")
        .option("cloudFiles.format", "parquet")
        .option("cloudFiles.maxFilesPerTrigger", 50)
        .option("cloudFiles.inferColumnTypes", True)
        .option("cloudFiles.schemaEvolutionMode", "addNewColumns")
        .option("cloudFiles.rescuedDataColumn", "_rescued_data")
        .load(
            "/Volumes/acme_edw_prod/edw_raw/incoming_volume/orders/region_MIDDLE_EAST/*.parquet"
        )
    )

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())
    df = df.withColumn("_source_file_path", F.col("_metadata.file_path"))

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_prod.edw_raw.orders_middle_east_raw",
    comment="Streaming table: orders_middle_east_raw",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_prod.edw_raw.orders_middle_east_raw",
    name="f_orders_middle_east_raw_cloudfiles",
    comment="Append flow to acme_edw_prod.edw_raw.orders_middle_east_raw",
)
def f_orders_middle_east_raw_cloudfiles():
    """Append flow to acme_edw_prod.edw_raw.orders_middle_east_raw"""
    # Streaming flow
    df = spark.readStream.table("v_orders_middle_east_raw_cloudfiles")

    return df
