# Generated by LakehousePlumber
# Pipeline: acme_edw_event_log_monitoring
# FlowGroup: monitoring

from pyspark import pipelines as dp
from pyspark.sql import DataFrame

# Pipeline Configuration
PIPELINE_ID = "acme_edw_event_log_monitoring"
FLOWGROUP_ID = "monitoring"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_all_event_logs():
    """SQL source: load_all_event_logs"""
    df = spark.sql("""SELECT *, 'acmi_edw_bronze' as _source_pipeline
FROM stream(acme_edw_dev._meta.acmi_edw_bronze_event_log)
UNION ALL
SELECT *, 'acmi_edw_modelled' as _source_pipeline
FROM stream(acme_edw_dev._meta.acmi_edw_modelled_event_log)
UNION ALL
SELECT *, 'acmi_edw_raw' as _source_pipeline
FROM stream(acme_edw_dev._meta.acmi_edw_raw_event_log)
UNION ALL
SELECT *, 'acmi_edw_silver' as _source_pipeline
FROM stream(acme_edw_dev._meta.acmi_edw_silver_event_log)
UNION ALL
SELECT *, 'custom_datasource' as _source_pipeline
FROM stream(acme_edw_dev._meta.custom_datasource_event_log)
UNION ALL
SELECT *, 'gold_load' as _source_pipeline
FROM stream(acme_edw_dev._meta.gold_load_event_log)
UNION ALL
SELECT *, 'kafka_sample_pipeline' as _source_pipeline
FROM stream(acme_edw_dev._meta.kafka_sample_pipeline_event_log)
UNION ALL
SELECT *, 'sample_python_func_pipeline' as _source_pipeline
FROM stream(acme_edw_dev._meta.sample_python_func_pipeline_event_log)""")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev._meta.custom_analysis",
    comment="Materialized view: custom_analysis",
    table_properties={},
)
def custom_analysis():
    """Write to acme_edw_dev._meta.custom_analysis from multiple sources"""
    # Materialized views use batch processing
    df = spark.sql("""SELECT
  _source_pipeline,
  event_type,
  date_trunc('DAY', timestamp) AS event_day,
  count(*) AS daily_event_count
FROM all_pipelines_event_log
WHERE event_type IN ('FLOW_PROGRESS', 'DATASET_CREATED')
GROUP BY _source_pipeline, event_type, date_trunc('DAY', timestamp)""")

    return df


# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev._meta.all_pipelines_event_log",
    comment="Streaming table: all_pipelines_event_log",
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev._meta.all_pipelines_event_log",
    name="f_all_event_logs",
    comment="Append flow to acme_edw_dev._meta.all_pipelines_event_log",
)
def f_all_event_logs():
    """Append flow to acme_edw_dev._meta.all_pipelines_event_log"""
    # Streaming flow
    df = spark.readStream.table("v_all_event_logs")

    return df
