# Generated by LakehousePlumber
# Pipeline: 14_jdbc_load
# FlowGroup: jdbc_query_mode

from pyspark.sql import DataFrame
from pyspark.sql import functions as F
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "14_jdbc_load"
FLOWGROUP_ID = "jdbc_query_mode"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_external_customers():
    """Load active customers from external PostgreSQL via JDBC query"""
    df = (
        spark.read.format("jdbc")
        .option("url", "jdbc:postgresql://example.com:5432/sample")
        .option("user", dbutils.secrets.get(scope="dev_db_secrets", key="username"))
        .option("password", dbutils.secrets.get(scope="dev_db_secrets", key="password"))
        .option("driver", "org.postgresql.Driver")
        .option(
            "query",
            """SELECT
  customer_id,
  first_name,
  last_name,
  email,
  registration_date
FROM customers
WHERE status = 'active'
""",
        )
        .load()
    )

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_bronze.jdbc_customers",
    comment="Materialized view of active customers from external JDBC source",
    table_properties={},
)
def jdbc_customers():
    """Write to acme_edw_dev.edw_bronze.jdbc_customers from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_external_customers")

    return df
