# Generated by LakehousePlumber
# Pipeline: 14_jdbc_load
# FlowGroup: jdbc_table_mode

from pyspark.sql import DataFrame
from pyspark import pipelines as dp

# Pipeline Configuration
PIPELINE_ID = "14_jdbc_load"
FLOWGROUP_ID = "jdbc_table_mode"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_external_products():
    """Load products table from external PostgreSQL via JDBC"""
    df = (
        spark.read.format("jdbc")
        .option("url", "jdbc:postgresql://example.com:5432/sample")
        .option("user", dbutils.secrets.get(scope="dev_db_secrets", key="username"))
        .option("password", dbutils.secrets.get(scope="dev_db_secrets", key="password"))
        .option("driver", "org.postgresql.Driver")
        .option("dbtable", "public.products")
        .load()
    )

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================


@dp.materialized_view(
    name="acme_edw_dev.edw_bronze.jdbc_products",
    comment="Materialized view of external JDBC products table",
    table_properties={},
)
def jdbc_products():
    """Write to acme_edw_dev.edw_bronze.jdbc_products from multiple sources"""
    # Materialized views use batch processing
    df = spark.read.table("v_external_products")

    return df
