# Generated by LakehousePlumber
# Pipeline: sample_python_func_pipeline
# FlowGroup: python_func_flowgroup

from custom_python_functions.sample_func import transform_lrc_data_streaming
from pyspark import pipelines as dp
from pyspark.sql import functions as F

# Pipeline Configuration
PIPELINE_ID = "sample_python_func_pipeline"
FLOWGROUP_ID = "python_func_flowgroup"


# ============================================================================
# SOURCE VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_raws():
    """Load customer table from raw schema"""
    df = spark.readStream.table("acme_edw_dev.edw_raw.customers")

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


# ============================================================================
# TRANSFORMATION VIEWS
# ============================================================================


@dp.temporary_view()
def v_customer_bronze_cleaneds():
    """Python transform: sample_func.transform_lrc_data_streaming"""
    # Load source view(s)
    v_customer_raws_df = spark.readStream.table("v_customer_raws")

    # Apply Python transformation
    parameters = {"spark": "spark", "parameters": {}}
    df = transform_lrc_data_streaming(v_customer_raws_df, spark, parameters)

    # Add operational metadata columns
    df = df.withColumn("_processing_timestamp", F.current_timestamp())

    return df


@dp.temporary_view()
# These expectations will fail the pipeline if violated
@dp.expect_all_or_fail(
    {
        "valid_custkey": "customer_id IS NOT NULL AND customer_id > 0",
        "valid_customer_name": "name IS NOT NULL AND LENGTH(TRIM(name)) > 0",
        "valid_nation_key": "nation_id IS NOT NULL AND nation_id >= 0",
    }
)
# These expectations will log warnings but not drop rows
@dp.expect_all(
    {
        "valid_phone_format": "phone IS NULL OR LENGTH(phone) >= 10",
        "valid_account_balance": "account_balance IS NULL OR account_balance >= -10000",
        "valid_market_segment": "market_segment IS NULL OR market_segment IN ('BUILDING', 'FURNITURE', 'HOUSEHOLD', 'MACHINERY')",
    }
)
def v_customer_bronze_DQEs():
    """Apply data quality checks to customer"""
    df = spark.readStream.table("v_customer_bronze_cleaneds")

    return df


# ============================================================================
# TARGET TABLES
# ============================================================================

# Create the streaming table
dp.create_streaming_table(
    name="acme_edw_dev.edw_bronze.customers",
    comment="Streaming table: customers",
    table_properties={
        "tag_name1": "tag_value1",
        "tag_name2": "tag_value2",
        "delta.enableRowTracking": "true",
    },
)


# Define append flow(s)
@dp.append_flow(
    target="acme_edw_dev.edw_bronze.customers",
    name="f_customer_bronze",
    comment="Append flow to acme_edw_dev.edw_bronze.customers",
)
def f_customer_bronze():
    """Append flow to acme_edw_dev.edw_bronze.customers"""
    # Streaming flow
    df = spark.readStream.table("v_customer_bronze_DQEs")

    return df
